/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import { type BudgetLine, BudgetLineFromJSON, BudgetLineToJSON } from '../models/BudgetLine'
import {
  type CrupdateBudgetLine,
  CrupdateBudgetLineFromJSON,
  CrupdateBudgetLineToJSON,
} from '../models/CrupdateBudgetLine'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'

export interface CrupdateBudgetLinesRequest {
  compId: string
  crupdateBudgetLine: Array<CrupdateBudgetLine>
}

export interface DeleteBudgetLineByIdRequest {
  compId: string
  id: string
}

export interface GetBudgetLineByIdRequest {
  compId: string
  id: string
}

export interface GetBudgetLinesRequest {
  compId: string
  page?: number
  pageSize?: number
}

/**
 *
 */
export class BudgetLineApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateBudgetLines without sending the request
   */
  async crupdateBudgetLinesRequestOpts(
    requestParameters: CrupdateBudgetLinesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateBudgetLines().',
      )
    }

    if (requestParameters['crupdateBudgetLine'] == null) {
      throw new runtime.RequiredError(
        'crupdateBudgetLine',
        'Required parameter "crupdateBudgetLine" was null or undefined when calling crupdateBudgetLines().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/budget_lines`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateBudgetLine']!.map(CrupdateBudgetLineToJSON),
    }
  }

  /**
   * Create new budget lines or update existing ones
   */
  async crupdateBudgetLinesRaw(
    requestParameters: CrupdateBudgetLinesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<BudgetLine>>> {
    const requestOptions = await this.crupdateBudgetLinesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BudgetLineFromJSON))
  }

  /**
   * Create new budget lines or update existing ones
   */
  async crupdateBudgetLines(
    requestParameters: CrupdateBudgetLinesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<BudgetLine>> {
    const response = await this.crupdateBudgetLinesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteBudgetLineById without sending the request
   */
  async deleteBudgetLineByIdRequestOpts(
    requestParameters: DeleteBudgetLineByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling deleteBudgetLineById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteBudgetLineById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/budget_lines/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete a budget line by identifier
   */
  async deleteBudgetLineByIdRaw(
    requestParameters: DeleteBudgetLineByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteBudgetLineByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete a budget line by identifier
   */
  async deleteBudgetLineById(
    requestParameters: DeleteBudgetLineByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteBudgetLineByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getBudgetLineById without sending the request
   */
  async getBudgetLineByIdRequestOpts(
    requestParameters: GetBudgetLineByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getBudgetLineById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getBudgetLineById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/budget_lines/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get a budget line by identifier
   */
  async getBudgetLineByIdRaw(
    requestParameters: GetBudgetLineByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<BudgetLine>> {
    const requestOptions = await this.getBudgetLineByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => BudgetLineFromJSON(jsonValue))
  }

  /**
   * Get a budget line by identifier
   */
  async getBudgetLineById(
    requestParameters: GetBudgetLineByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<BudgetLine> {
    const response = await this.getBudgetLineByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getBudgetLines without sending the request
   */
  async getBudgetLinesRequestOpts(
    requestParameters: GetBudgetLinesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getBudgetLines().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['page_size'] = requestParameters['pageSize']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/budget_lines`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all budget lines
   */
  async getBudgetLinesRaw(
    requestParameters: GetBudgetLinesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<BudgetLine>>> {
    const requestOptions = await this.getBudgetLinesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BudgetLineFromJSON))
  }

  /**
   * Get all budget lines
   */
  async getBudgetLines(
    requestParameters: GetBudgetLinesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<BudgetLine>> {
    const response = await this.getBudgetLinesRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
