/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import {
  type CashTransaction,
  CashTransactionFromJSON,
  CashTransactionToJSON,
} from '../models/CashTransaction'
import {
  type CrupdateCashTransaction,
  CrupdateCashTransactionFromJSON,
  CrupdateCashTransactionToJSON,
} from '../models/CrupdateCashTransaction'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'

export interface CrupdateCashTransactionsRequest {
  compId: string
  accountId: string
  crupdateCashTransaction: Array<CrupdateCashTransaction>
}

export interface DeleteCashTransactionByIdRequest {
  compId: string
  accountId: string
  id: string
}

export interface GetCashTransactionByIdRequest {
  compId: string
  accountId: string
  id: string
}

export interface GetCashTransactionsRequest {
  compId: string
  accountId: string
  page?: number
  pageSize?: number
}

/**
 *
 */
export class CashTransactionApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateCashTransactions without sending the request
   */
  async crupdateCashTransactionsRequestOpts(
    requestParameters: CrupdateCashTransactionsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateCashTransactions().',
      )
    }

    if (requestParameters['accountId'] == null) {
      throw new runtime.RequiredError(
        'accountId',
        'Required parameter "accountId" was null or undefined when calling crupdateCashTransactions().',
      )
    }

    if (requestParameters['crupdateCashTransaction'] == null) {
      throw new runtime.RequiredError(
        'crupdateCashTransaction',
        'Required parameter "crupdateCashTransaction" was null or undefined when calling crupdateCashTransactions().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/cash_accounts/{account_id}/transactions`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace(
      '{account_id}',
      encodeURIComponent(String(requestParameters['accountId'])),
    )

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateCashTransaction']!.map(CrupdateCashTransactionToJSON),
    }
  }

  /**
   * Create new cash transactions or update existing ones
   */
  async crupdateCashTransactionsRaw(
    requestParameters: CrupdateCashTransactionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<CashTransaction>>> {
    const requestOptions = await this.crupdateCashTransactionsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(CashTransactionFromJSON),
    )
  }

  /**
   * Create new cash transactions or update existing ones
   */
  async crupdateCashTransactions(
    requestParameters: CrupdateCashTransactionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<CashTransaction>> {
    const response = await this.crupdateCashTransactionsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteCashTransactionById without sending the request
   */
  async deleteCashTransactionByIdRequestOpts(
    requestParameters: DeleteCashTransactionByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling deleteCashTransactionById().',
      )
    }

    if (requestParameters['accountId'] == null) {
      throw new runtime.RequiredError(
        'accountId',
        'Required parameter "accountId" was null or undefined when calling deleteCashTransactionById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteCashTransactionById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/cash_accounts/{account_id}/transactions/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace(
      '{account_id}',
      encodeURIComponent(String(requestParameters['accountId'])),
    )
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete a cash transaction by identifier
   */
  async deleteCashTransactionByIdRaw(
    requestParameters: DeleteCashTransactionByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteCashTransactionByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete a cash transaction by identifier
   */
  async deleteCashTransactionById(
    requestParameters: DeleteCashTransactionByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteCashTransactionByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getCashTransactionById without sending the request
   */
  async getCashTransactionByIdRequestOpts(
    requestParameters: GetCashTransactionByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getCashTransactionById().',
      )
    }

    if (requestParameters['accountId'] == null) {
      throw new runtime.RequiredError(
        'accountId',
        'Required parameter "accountId" was null or undefined when calling getCashTransactionById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getCashTransactionById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/cash_accounts/{account_id}/transactions/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace(
      '{account_id}',
      encodeURIComponent(String(requestParameters['accountId'])),
    )
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get a cash transaction by identifier
   */
  async getCashTransactionByIdRaw(
    requestParameters: GetCashTransactionByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CashTransaction>> {
    const requestOptions = await this.getCashTransactionByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => CashTransactionFromJSON(jsonValue))
  }

  /**
   * Get a cash transaction by identifier
   */
  async getCashTransactionById(
    requestParameters: GetCashTransactionByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CashTransaction> {
    const response = await this.getCashTransactionByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getCashTransactions without sending the request
   */
  async getCashTransactionsRequestOpts(
    requestParameters: GetCashTransactionsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getCashTransactions().',
      )
    }

    if (requestParameters['accountId'] == null) {
      throw new runtime.RequiredError(
        'accountId',
        'Required parameter "accountId" was null or undefined when calling getCashTransactions().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['page_size'] = requestParameters['pageSize']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/cash_accounts/{account_id}/transactions`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace(
      '{account_id}',
      encodeURIComponent(String(requestParameters['accountId'])),
    )

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all cash transactions for an account
   */
  async getCashTransactionsRaw(
    requestParameters: GetCashTransactionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<CashTransaction>>> {
    const requestOptions = await this.getCashTransactionsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(CashTransactionFromJSON),
    )
  }

  /**
   * Get all cash transactions for an account
   */
  async getCashTransactions(
    requestParameters: GetCashTransactionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<CashTransaction>> {
    const response = await this.getCashTransactionsRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
