/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import { type CashAccount, CashAccountFromJSON, CashAccountToJSON } from '../models/CashAccount'
import {
  type CrupdateCashAccount,
  CrupdateCashAccountFromJSON,
  CrupdateCashAccountToJSON,
} from '../models/CrupdateCashAccount'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'

export interface CrupdateCashAccountsRequest {
  compId: string
  crupdateCashAccount: Array<CrupdateCashAccount>
}

export interface DeleteCashAccountByIdRequest {
  compId: string
  id: string
}

export interface GetCashAccountByIdRequest {
  compId: string
  id: string
}

export interface GetCashAccountsRequest {
  compId: string
  page?: number
  pageSize?: number
}

/**
 *
 */
export class CashAccountApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateCashAccounts without sending the request
   */
  async crupdateCashAccountsRequestOpts(
    requestParameters: CrupdateCashAccountsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateCashAccounts().',
      )
    }

    if (requestParameters['crupdateCashAccount'] == null) {
      throw new runtime.RequiredError(
        'crupdateCashAccount',
        'Required parameter "crupdateCashAccount" was null or undefined when calling crupdateCashAccounts().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/cash_accounts`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateCashAccount']!.map(CrupdateCashAccountToJSON),
    }
  }

  /**
   * Create new cash accounts or update existing ones
   */
  async crupdateCashAccountsRaw(
    requestParameters: CrupdateCashAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<CashAccount>>> {
    const requestOptions = await this.crupdateCashAccountsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CashAccountFromJSON))
  }

  /**
   * Create new cash accounts or update existing ones
   */
  async crupdateCashAccounts(
    requestParameters: CrupdateCashAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<CashAccount>> {
    const response = await this.crupdateCashAccountsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteCashAccountById without sending the request
   */
  async deleteCashAccountByIdRequestOpts(
    requestParameters: DeleteCashAccountByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling deleteCashAccountById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteCashAccountById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/cash_accounts/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete a cash account by identifier
   */
  async deleteCashAccountByIdRaw(
    requestParameters: DeleteCashAccountByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteCashAccountByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete a cash account by identifier
   */
  async deleteCashAccountById(
    requestParameters: DeleteCashAccountByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteCashAccountByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getCashAccountById without sending the request
   */
  async getCashAccountByIdRequestOpts(
    requestParameters: GetCashAccountByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getCashAccountById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getCashAccountById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/cash_accounts/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get a cash account by identifier
   */
  async getCashAccountByIdRaw(
    requestParameters: GetCashAccountByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CashAccount>> {
    const requestOptions = await this.getCashAccountByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => CashAccountFromJSON(jsonValue))
  }

  /**
   * Get a cash account by identifier
   */
  async getCashAccountById(
    requestParameters: GetCashAccountByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CashAccount> {
    const response = await this.getCashAccountByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getCashAccounts without sending the request
   */
  async getCashAccountsRequestOpts(
    requestParameters: GetCashAccountsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getCashAccounts().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['page_size'] = requestParameters['pageSize']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/cash_accounts`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all cash accounts
   */
  async getCashAccountsRaw(
    requestParameters: GetCashAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<CashAccount>>> {
    const requestOptions = await this.getCashAccountsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CashAccountFromJSON))
  }

  /**
   * Get all cash accounts
   */
  async getCashAccounts(
    requestParameters: GetCashAccountsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<CashAccount>> {
    const response = await this.getCashAccountsRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
