/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import {
  type CrupdateDepartment,
  CrupdateDepartmentFromJSON,
  CrupdateDepartmentToJSON,
} from '../models/CrupdateDepartment'
import { type Department, DepartmentFromJSON, DepartmentToJSON } from '../models/Department'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'

export interface CrupdateDepartmentsRequest {
  compId: string
  crupdateDepartment: Array<CrupdateDepartment>
}

export interface DeleteDepartmentByIdRequest {
  compId: string
  id: string
}

export interface GetDepartmentByIdRequest {
  compId: string
  id: string
}

export interface GetDepartmentsRequest {
  compId: string
  page?: number
  pageSize?: number
}

/**
 *
 */
export class DepartmentApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateDepartments without sending the request
   */
  async crupdateDepartmentsRequestOpts(
    requestParameters: CrupdateDepartmentsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateDepartments().',
      )
    }

    if (requestParameters['crupdateDepartment'] == null) {
      throw new runtime.RequiredError(
        'crupdateDepartment',
        'Required parameter "crupdateDepartment" was null or undefined when calling crupdateDepartments().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/departments`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateDepartment']!.map(CrupdateDepartmentToJSON),
    }
  }

  /**
   * Create new departments or update existing ones
   */
  async crupdateDepartmentsRaw(
    requestParameters: CrupdateDepartmentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Department>>> {
    const requestOptions = await this.crupdateDepartmentsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DepartmentFromJSON))
  }

  /**
   * Create new departments or update existing ones
   */
  async crupdateDepartments(
    requestParameters: CrupdateDepartmentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Department>> {
    const response = await this.crupdateDepartmentsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteDepartmentById without sending the request
   */
  async deleteDepartmentByIdRequestOpts(
    requestParameters: DeleteDepartmentByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling deleteDepartmentById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteDepartmentById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/departments/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete a department by identifier
   */
  async deleteDepartmentByIdRaw(
    requestParameters: DeleteDepartmentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteDepartmentByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete a department by identifier
   */
  async deleteDepartmentById(
    requestParameters: DeleteDepartmentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteDepartmentByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getDepartmentById without sending the request
   */
  async getDepartmentByIdRequestOpts(
    requestParameters: GetDepartmentByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getDepartmentById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getDepartmentById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/departments/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get a department by identifier
   */
  async getDepartmentByIdRaw(
    requestParameters: GetDepartmentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Department>> {
    const requestOptions = await this.getDepartmentByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentFromJSON(jsonValue))
  }

  /**
   * Get a department by identifier
   */
  async getDepartmentById(
    requestParameters: GetDepartmentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Department> {
    const response = await this.getDepartmentByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getDepartments without sending the request
   */
  async getDepartmentsRequestOpts(
    requestParameters: GetDepartmentsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getDepartments().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['page_size'] = requestParameters['pageSize']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/departments`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all departments
   */
  async getDepartmentsRaw(
    requestParameters: GetDepartmentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Department>>> {
    const requestOptions = await this.getDepartmentsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DepartmentFromJSON))
  }

  /**
   * Get all departments
   */
  async getDepartments(
    requestParameters: GetDepartmentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Department>> {
    const response = await this.getDepartmentsRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
