/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BadRequestException,
    BadRequestExceptionFromJSON,
    BadRequestExceptionToJSON,
} from '../models/BadRequestException';
import {
    type CrupdateEquipmentIncident,
    CrupdateEquipmentIncidentFromJSON,
    CrupdateEquipmentIncidentToJSON,
} from '../models/CrupdateEquipmentIncident';
import {
    type EquipmentIncident,
    EquipmentIncidentFromJSON,
    EquipmentIncidentToJSON,
} from '../models/EquipmentIncident';
import {
    type IncidentType,
    IncidentTypeFromJSON,
    IncidentTypeToJSON,
} from '../models/IncidentType';
import {
    type InternalServerException,
    InternalServerExceptionFromJSON,
    InternalServerExceptionToJSON,
} from '../models/InternalServerException';
import {
    type NotAuthorizedException,
    NotAuthorizedExceptionFromJSON,
    NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException';
import {
    type PaginatedResponse,
    PaginatedResponseFromJSON,
    PaginatedResponseToJSON,
} from '../models/PaginatedResponse';
import {
    type ResourceNotFoundException,
    ResourceNotFoundExceptionFromJSON,
    ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException';
import {
    type TooManyRequestsException,
    TooManyRequestsExceptionFromJSON,
    TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException';

export interface CrupdateEquipmentIncidentsRequest {
    userId: string;
    companyId: string;
    crupdateEquipmentIncident: Array<CrupdateEquipmentIncident>;
}

export interface DeleteEquipmentIncidentByIdRequest {
    userId: string;
    companyId: string;
    id: string;
}

export interface GetEquipmentIncidentByIdRequest {
    userId: string;
    companyId: string;
    id: string;
}

export interface GetEquipmentIncidentsRequest {
    userId: string;
    companyId: string;
    page?: number;
    pageSize?: number;
    equipmentId?: string;
    incidentType?: IncidentType;
    userId2?: string;
    travelId?: string;
}

/**
 * 
 */
export class EquipmentIncidentApi extends runtime.BaseAPI {

    /**
     * Creates request options for crupdateEquipmentIncidents without sending the request
     */
    async crupdateEquipmentIncidentsRequestOpts(requestParameters: CrupdateEquipmentIncidentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling crupdateEquipmentIncidents().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling crupdateEquipmentIncidents().'
            );
        }

        if (requestParameters['crupdateEquipmentIncident'] == null) {
            throw new runtime.RequiredError(
                'crupdateEquipmentIncident',
                'Required parameter "crupdateEquipmentIncident" was null or undefined when calling crupdateEquipmentIncidents().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/equipment_incidents`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['crupdateEquipmentIncident']!.map(CrupdateEquipmentIncidentToJSON),
        };
    }

    /**
     * Create new equipment incident or update existing equipment incident
     */
    async crupdateEquipmentIncidentsRaw(requestParameters: CrupdateEquipmentIncidentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EquipmentIncident>>> {
        const requestOptions = await this.crupdateEquipmentIncidentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EquipmentIncidentFromJSON));
    }

    /**
     * Create new equipment incident or update existing equipment incident
     */
    async crupdateEquipmentIncidents(requestParameters: CrupdateEquipmentIncidentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EquipmentIncident>> {
        const response = await this.crupdateEquipmentIncidentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEquipmentIncidentById without sending the request
     */
    async deleteEquipmentIncidentByIdRequestOpts(requestParameters: DeleteEquipmentIncidentByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteEquipmentIncidentById().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling deleteEquipmentIncidentById().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEquipmentIncidentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/equipment_incidents/{id}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete equipment incident by identifier (Admin only)
     */
    async deleteEquipmentIncidentByIdRaw(requestParameters: DeleteEquipmentIncidentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteEquipmentIncidentByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete equipment incident by identifier (Admin only)
     */
    async deleteEquipmentIncidentById(requestParameters: DeleteEquipmentIncidentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEquipmentIncidentByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getEquipmentIncidentById without sending the request
     */
    async getEquipmentIncidentByIdRequestOpts(requestParameters: GetEquipmentIncidentByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getEquipmentIncidentById().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getEquipmentIncidentById().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEquipmentIncidentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/equipment_incidents/{id}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get equipment incident by identifier
     */
    async getEquipmentIncidentByIdRaw(requestParameters: GetEquipmentIncidentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentIncident>> {
        const requestOptions = await this.getEquipmentIncidentByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentIncidentFromJSON(jsonValue));
    }

    /**
     * Get equipment incident by identifier
     */
    async getEquipmentIncidentById(requestParameters: GetEquipmentIncidentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentIncident> {
        const response = await this.getEquipmentIncidentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEquipmentIncidents without sending the request
     */
    async getEquipmentIncidentsRequestOpts(requestParameters: GetEquipmentIncidentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getEquipmentIncidents().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getEquipmentIncidents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['equipmentId'] != null) {
            queryParameters['equipment_id'] = requestParameters['equipmentId'];
        }

        if (requestParameters['incidentType'] != null) {
            queryParameters['incident_type'] = requestParameters['incidentType'];
        }

        if (requestParameters['userId2'] != null) {
            queryParameters['user_id'] = requestParameters['userId2'];
        }

        if (requestParameters['travelId'] != null) {
            queryParameters['travel_id'] = requestParameters['travelId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/equipment_incidents`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all equipment incidents
     */
    async getEquipmentIncidentsRaw(requestParameters: GetEquipmentIncidentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponse>> {
        const requestOptions = await this.getEquipmentIncidentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get all equipment incidents
     */
    async getEquipmentIncidents(requestParameters: GetEquipmentIncidentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponse> {
        const response = await this.getEquipmentIncidentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
