/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BadRequestException,
    BadRequestExceptionFromJSON,
    BadRequestExceptionToJSON,
} from '../models/BadRequestException';
import {
    type CrupdateExpenseMoney,
    CrupdateExpenseMoneyFromJSON,
    CrupdateExpenseMoneyToJSON,
} from '../models/CrupdateExpenseMoney';
import {
    type ExpenseMoney,
    ExpenseMoneyFromJSON,
    ExpenseMoneyToJSON,
} from '../models/ExpenseMoney';
import {
    type InternalServerException,
    InternalServerExceptionFromJSON,
    InternalServerExceptionToJSON,
} from '../models/InternalServerException';
import {
    type NotAuthorizedException,
    NotAuthorizedExceptionFromJSON,
    NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException';
import {
    type ResourceNotFoundException,
    ResourceNotFoundExceptionFromJSON,
    ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException';
import {
    type TooManyRequestsException,
    TooManyRequestsExceptionFromJSON,
    TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException';

export interface CrupdateExpensesRequest {
    compId: string;
    jobId: string;
    userId: string;
    crupdateExpenseMoney: Array<CrupdateExpenseMoney>;
}

export interface DeleteExpenseByIdRequest {
    compId: string;
    jobId: string;
    userId: string;
    id: string;
}

export interface GetExpenseByIdRequest {
    compId: string;
    jobId: string;
    userId: string;
    id: string;
}

export interface GetExpensesRequest {
    compId: string;
    jobId: string;
    userId: string;
    page?: number;
    pageSize?: number;
    description?: string;
    amount?: number;
}

/**
 * 
 */
export class ExpenseApi extends runtime.BaseAPI {

    /**
     * Creates request options for crupdateExpenses without sending the request
     */
    async crupdateExpensesRequestOpts(requestParameters: CrupdateExpensesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['compId'] == null) {
            throw new runtime.RequiredError(
                'compId',
                'Required parameter "compId" was null or undefined when calling crupdateExpenses().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling crupdateExpenses().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling crupdateExpenses().'
            );
        }

        if (requestParameters['crupdateExpenseMoney'] == null) {
            throw new runtime.RequiredError(
                'crupdateExpenseMoney',
                'Required parameter "crupdateExpenseMoney" was null or undefined when calling crupdateExpenses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses`;
        urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])));
        urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['crupdateExpenseMoney']!.map(CrupdateExpenseMoneyToJSON),
        };
    }

    /**
     * Create new expenses or update existing ones
     */
    async crupdateExpensesRaw(requestParameters: CrupdateExpensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExpenseMoney>>> {
        const requestOptions = await this.crupdateExpensesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExpenseMoneyFromJSON));
    }

    /**
     * Create new expenses or update existing ones
     */
    async crupdateExpenses(requestParameters: CrupdateExpensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExpenseMoney>> {
        const response = await this.crupdateExpensesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteExpenseById without sending the request
     */
    async deleteExpenseByIdRequestOpts(requestParameters: DeleteExpenseByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['compId'] == null) {
            throw new runtime.RequiredError(
                'compId',
                'Required parameter "compId" was null or undefined when calling deleteExpenseById().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling deleteExpenseById().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteExpenseById().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteExpenseById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{id}`;
        urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])));
        urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete expense by identifier
     */
    async deleteExpenseByIdRaw(requestParameters: DeleteExpenseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteExpenseByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete expense by identifier
     */
    async deleteExpenseById(requestParameters: DeleteExpenseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteExpenseByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getExpenseById without sending the request
     */
    async getExpenseByIdRequestOpts(requestParameters: GetExpenseByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['compId'] == null) {
            throw new runtime.RequiredError(
                'compId',
                'Required parameter "compId" was null or undefined when calling getExpenseById().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getExpenseById().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getExpenseById().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getExpenseById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{id}`;
        urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])));
        urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get expense by identifier
     */
    async getExpenseByIdRaw(requestParameters: GetExpenseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseMoney>> {
        const requestOptions = await this.getExpenseByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseMoneyFromJSON(jsonValue));
    }

    /**
     * Get expense by identifier
     */
    async getExpenseById(requestParameters: GetExpenseByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseMoney> {
        const response = await this.getExpenseByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExpenses without sending the request
     */
    async getExpensesRequestOpts(requestParameters: GetExpensesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['compId'] == null) {
            throw new runtime.RequiredError(
                'compId',
                'Required parameter "compId" was null or undefined when calling getExpenses().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getExpenses().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getExpenses().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['description'] != null) {
            queryParameters['description'] = requestParameters['description'];
        }

        if (requestParameters['amount'] != null) {
            queryParameters['amount'] = requestParameters['amount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses`;
        urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])));
        urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all expenses
     */
    async getExpensesRaw(requestParameters: GetExpensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExpenseMoney>>> {
        const requestOptions = await this.getExpensesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExpenseMoneyFromJSON));
    }

    /**
     * Get all expenses
     */
    async getExpenses(requestParameters: GetExpensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExpenseMoney>> {
        const response = await this.getExpensesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
