/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import {
  type CrupdateEmployeeLeaveConfig,
  CrupdateEmployeeLeaveConfigFromJSON,
  CrupdateEmployeeLeaveConfigToJSON,
} from '../models/CrupdateEmployeeLeaveConfig'
import {
  type CrupdateLeave,
  CrupdateLeaveFromJSON,
  CrupdateLeaveToJSON,
} from '../models/CrupdateLeave'
import {
  type CrupdateLeaveType,
  CrupdateLeaveTypeFromJSON,
  CrupdateLeaveTypeToJSON,
} from '../models/CrupdateLeaveType'
import { type CrupdateUser, CrupdateUserFromJSON, CrupdateUserToJSON } from '../models/CrupdateUser'
import {
  type EmployeeLeaveConfig,
  EmployeeLeaveConfigFromJSON,
  EmployeeLeaveConfigToJSON,
} from '../models/EmployeeLeaveConfig'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import { type Leave, LeaveFromJSON, LeaveToJSON } from '../models/Leave'
import { type LeaveBalance, LeaveBalanceFromJSON, LeaveBalanceToJSON } from '../models/LeaveBalance'
import { type LeaveType, LeaveTypeFromJSON, LeaveTypeToJSON } from '../models/LeaveType'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'

export interface CrupdateEmployeeLeaveConfigsRequest {
  compId: string
  crupdateEmployeeLeaveConfig: Array<CrupdateEmployeeLeaveConfig>
}

export interface CrupdateLeaveTypesRequest {
  compId: string
  crupdateLeaveType: Array<CrupdateLeaveType>
}

export interface CrupdateLeavesRequest {
  compId: string
  crupdateLeave: Array<CrupdateLeave>
}

export interface DeleteLeaveByIdRequest {
  compId: string
  id: string
}

export interface GetEmployeeLeaveConfigByUserIdRequest {
  compId: string
  userId: string
}

export interface GetEmployeeLeaveConfigsRequest {
  compId: string
}

export interface GetEmployeesWithoutLeaveRequest {
  compId: string
  year: number
}

export interface GetLeaveBalancesRequest {
  compId: string
  year: number
}

export interface GetLeaveByIdRequest {
  compId: string
  id: string
}

export interface GetLeaveTypesRequest {
  compId: string
}

export interface GetLeavesRequest {
  compId: string
  userId?: string
  leaveTypeId?: string
  status?: string
  year?: number
  page?: number
  pageSize?: number
}

/**
 *
 */
export class HRApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateEmployeeLeaveConfigs without sending the request
   */
  async crupdateEmployeeLeaveConfigsRequestOpts(
    requestParameters: CrupdateEmployeeLeaveConfigsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateEmployeeLeaveConfigs().',
      )
    }

    if (requestParameters['crupdateEmployeeLeaveConfig'] == null) {
      throw new runtime.RequiredError(
        'crupdateEmployeeLeaveConfig',
        'Required parameter "crupdateEmployeeLeaveConfig" was null or undefined when calling crupdateEmployeeLeaveConfigs().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leave-configs`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateEmployeeLeaveConfig']!.map(
        CrupdateEmployeeLeaveConfigToJSON,
      ),
    }
  }

  /**
   * Create or update employee leave configs
   */
  async crupdateEmployeeLeaveConfigsRaw(
    requestParameters: CrupdateEmployeeLeaveConfigsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<EmployeeLeaveConfig>>> {
    const requestOptions = await this.crupdateEmployeeLeaveConfigsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(EmployeeLeaveConfigFromJSON),
    )
  }

  /**
   * Create or update employee leave configs
   */
  async crupdateEmployeeLeaveConfigs(
    requestParameters: CrupdateEmployeeLeaveConfigsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<EmployeeLeaveConfig>> {
    const response = await this.crupdateEmployeeLeaveConfigsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for crupdateLeaveTypes without sending the request
   */
  async crupdateLeaveTypesRequestOpts(
    requestParameters: CrupdateLeaveTypesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateLeaveTypes().',
      )
    }

    if (requestParameters['crupdateLeaveType'] == null) {
      throw new runtime.RequiredError(
        'crupdateLeaveType',
        'Required parameter "crupdateLeaveType" was null or undefined when calling crupdateLeaveTypes().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leave-types`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateLeaveType']!.map(CrupdateLeaveTypeToJSON),
    }
  }

  /**
   * Create or update leave types
   */
  async crupdateLeaveTypesRaw(
    requestParameters: CrupdateLeaveTypesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LeaveType>>> {
    const requestOptions = await this.crupdateLeaveTypesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LeaveTypeFromJSON))
  }

  /**
   * Create or update leave types
   */
  async crupdateLeaveTypes(
    requestParameters: CrupdateLeaveTypesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LeaveType>> {
    const response = await this.crupdateLeaveTypesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for crupdateLeaves without sending the request
   */
  async crupdateLeavesRequestOpts(
    requestParameters: CrupdateLeavesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateLeaves().',
      )
    }

    if (requestParameters['crupdateLeave'] == null) {
      throw new runtime.RequiredError(
        'crupdateLeave',
        'Required parameter "crupdateLeave" was null or undefined when calling crupdateLeaves().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leaves`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateLeave']!.map(CrupdateLeaveToJSON),
    }
  }

  /**
   * Create or update leaves
   */
  async crupdateLeavesRaw(
    requestParameters: CrupdateLeavesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Leave>>> {
    const requestOptions = await this.crupdateLeavesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LeaveFromJSON))
  }

  /**
   * Create or update leaves
   */
  async crupdateLeaves(
    requestParameters: CrupdateLeavesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Leave>> {
    const response = await this.crupdateLeavesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteLeaveById without sending the request
   */
  async deleteLeaveByIdRequestOpts(
    requestParameters: DeleteLeaveByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling deleteLeaveById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteLeaveById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leaves/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete leave by identifier
   */
  async deleteLeaveByIdRaw(
    requestParameters: DeleteLeaveByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteLeaveByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete leave by identifier
   */
  async deleteLeaveById(
    requestParameters: DeleteLeaveByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteLeaveByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getEmployeeLeaveConfigByUserId without sending the request
   */
  async getEmployeeLeaveConfigByUserIdRequestOpts(
    requestParameters: GetEmployeeLeaveConfigByUserIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getEmployeeLeaveConfigByUserId().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getEmployeeLeaveConfigByUserId().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leave-configs/{user_id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get leave config for a specific user
   */
  async getEmployeeLeaveConfigByUserIdRaw(
    requestParameters: GetEmployeeLeaveConfigByUserIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EmployeeLeaveConfig>> {
    const requestOptions = await this.getEmployeeLeaveConfigByUserIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EmployeeLeaveConfigFromJSON(jsonValue),
    )
  }

  /**
   * Get leave config for a specific user
   */
  async getEmployeeLeaveConfigByUserId(
    requestParameters: GetEmployeeLeaveConfigByUserIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EmployeeLeaveConfig> {
    const response = await this.getEmployeeLeaveConfigByUserIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getEmployeeLeaveConfigs without sending the request
   */
  async getEmployeeLeaveConfigsRequestOpts(
    requestParameters: GetEmployeeLeaveConfigsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getEmployeeLeaveConfigs().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leave-configs`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all employee leave configs
   */
  async getEmployeeLeaveConfigsRaw(
    requestParameters: GetEmployeeLeaveConfigsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<EmployeeLeaveConfig>>> {
    const requestOptions = await this.getEmployeeLeaveConfigsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(EmployeeLeaveConfigFromJSON),
    )
  }

  /**
   * Get all employee leave configs
   */
  async getEmployeeLeaveConfigs(
    requestParameters: GetEmployeeLeaveConfigsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<EmployeeLeaveConfig>> {
    const response = await this.getEmployeeLeaveConfigsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getEmployeesWithoutLeave without sending the request
   */
  async getEmployeesWithoutLeaveRequestOpts(
    requestParameters: GetEmployeesWithoutLeaveRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getEmployeesWithoutLeave().',
      )
    }

    if (requestParameters['year'] == null) {
      throw new runtime.RequiredError(
        'year',
        'Required parameter "year" was null or undefined when calling getEmployeesWithoutLeave().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['year'] != null) {
      queryParameters['year'] = requestParameters['year']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leave-balances/employees-without-leave`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get employees who haven\'t taken any leave
   */
  async getEmployeesWithoutLeaveRaw(
    requestParameters: GetEmployeesWithoutLeaveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<CrupdateUser>>> {
    const requestOptions = await this.getEmployeesWithoutLeaveRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CrupdateUserFromJSON))
  }

  /**
   * Get employees who haven\'t taken any leave
   */
  async getEmployeesWithoutLeave(
    requestParameters: GetEmployeesWithoutLeaveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<CrupdateUser>> {
    const response = await this.getEmployeesWithoutLeaveRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getLeaveBalances without sending the request
   */
  async getLeaveBalancesRequestOpts(
    requestParameters: GetLeaveBalancesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getLeaveBalances().',
      )
    }

    if (requestParameters['year'] == null) {
      throw new runtime.RequiredError(
        'year',
        'Required parameter "year" was null or undefined when calling getLeaveBalances().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['year'] != null) {
      queryParameters['year'] = requestParameters['year']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leave-balances`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get leave balances for all employees in a company
   */
  async getLeaveBalancesRaw(
    requestParameters: GetLeaveBalancesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LeaveBalance>>> {
    const requestOptions = await this.getLeaveBalancesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LeaveBalanceFromJSON))
  }

  /**
   * Get leave balances for all employees in a company
   */
  async getLeaveBalances(
    requestParameters: GetLeaveBalancesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LeaveBalance>> {
    const response = await this.getLeaveBalancesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getLeaveById without sending the request
   */
  async getLeaveByIdRequestOpts(
    requestParameters: GetLeaveByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getLeaveById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getLeaveById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leaves/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get leave by identifier
   */
  async getLeaveByIdRaw(
    requestParameters: GetLeaveByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Leave>> {
    const requestOptions = await this.getLeaveByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => LeaveFromJSON(jsonValue))
  }

  /**
   * Get leave by identifier
   */
  async getLeaveById(
    requestParameters: GetLeaveByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Leave> {
    const response = await this.getLeaveByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getLeaveTypes without sending the request
   */
  async getLeaveTypesRequestOpts(
    requestParameters: GetLeaveTypesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getLeaveTypes().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leave-types`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all leave types
   */
  async getLeaveTypesRaw(
    requestParameters: GetLeaveTypesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LeaveType>>> {
    const requestOptions = await this.getLeaveTypesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LeaveTypeFromJSON))
  }

  /**
   * Get all leave types
   */
  async getLeaveTypes(
    requestParameters: GetLeaveTypesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LeaveType>> {
    const response = await this.getLeaveTypesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getLeaves without sending the request
   */
  async getLeavesRequestOpts(requestParameters: GetLeavesRequest): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getLeaves().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['userId'] != null) {
      queryParameters['user_id'] = requestParameters['userId']
    }

    if (requestParameters['leaveTypeId'] != null) {
      queryParameters['leave_type_id'] = requestParameters['leaveTypeId']
    }

    if (requestParameters['status'] != null) {
      queryParameters['status'] = requestParameters['status']
    }

    if (requestParameters['year'] != null) {
      queryParameters['year'] = requestParameters['year']
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['page_size'] = requestParameters['pageSize']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/leaves`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all leaves
   */
  async getLeavesRaw(
    requestParameters: GetLeavesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Leave>>> {
    const requestOptions = await this.getLeavesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LeaveFromJSON))
  }

  /**
   * Get all leaves
   */
  async getLeaves(
    requestParameters: GetLeavesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Leave>> {
    const response = await this.getLeavesRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
