/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import {
  type CrupdateIncomeMoney,
  CrupdateIncomeMoneyFromJSON,
  CrupdateIncomeMoneyToJSON,
} from '../models/CrupdateIncomeMoney'
import { type IncomeMoney, IncomeMoneyFromJSON, IncomeMoneyToJSON } from '../models/IncomeMoney'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'

export interface CrupdateIncomesRequest {
  compId: string
  jobId: string
  userId: string
  crupdateIncomeMoney: Array<CrupdateIncomeMoney>
}

export interface DeleteIncomeByIdRequest {
  compId: string
  jobId: string
  userId: string
  id: string
}

export interface GetIncomeByIdRequest {
  compId: string
  jobId: string
  userId: string
  id: string
}

export interface GetIncomesRequest {
  compId: string
  jobId: string
  userId: string
  page?: number
  pageSize?: number
  sourceOrganization?: string
  invoiceReference?: string
  description?: string
  amount?: number
  incomeTypeId?: string
  moneyReceived?: boolean
}

/**
 *
 */
export class IncomeApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateIncomes without sending the request
   */
  async crupdateIncomesRequestOpts(
    requestParameters: CrupdateIncomesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateIncomes().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling crupdateIncomes().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling crupdateIncomes().',
      )
    }

    if (requestParameters['crupdateIncomeMoney'] == null) {
      throw new runtime.RequiredError(
        'crupdateIncomeMoney',
        'Required parameter "crupdateIncomeMoney" was null or undefined when calling crupdateIncomes().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/incomes`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateIncomeMoney']!.map(CrupdateIncomeMoneyToJSON),
    }
  }

  /**
   * Create new incomes or update existing ones
   */
  async crupdateIncomesRaw(
    requestParameters: CrupdateIncomesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<IncomeMoney>>> {
    const requestOptions = await this.crupdateIncomesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IncomeMoneyFromJSON))
  }

  /**
   * Create new incomes or update existing ones
   */
  async crupdateIncomes(
    requestParameters: CrupdateIncomesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<IncomeMoney>> {
    const response = await this.crupdateIncomesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteIncomeById without sending the request
   */
  async deleteIncomeByIdRequestOpts(
    requestParameters: DeleteIncomeByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling deleteIncomeById().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling deleteIncomeById().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling deleteIncomeById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteIncomeById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/incomes/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete income by identifier
   */
  async deleteIncomeByIdRaw(
    requestParameters: DeleteIncomeByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteIncomeByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete income by identifier
   */
  async deleteIncomeById(
    requestParameters: DeleteIncomeByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteIncomeByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getIncomeById without sending the request
   */
  async getIncomeByIdRequestOpts(
    requestParameters: GetIncomeByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getIncomeById().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling getIncomeById().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getIncomeById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getIncomeById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/incomes/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get income by identifier
   */
  async getIncomeByIdRaw(
    requestParameters: GetIncomeByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<IncomeMoney>> {
    const requestOptions = await this.getIncomeByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => IncomeMoneyFromJSON(jsonValue))
  }

  /**
   * Get income by identifier
   */
  async getIncomeById(
    requestParameters: GetIncomeByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<IncomeMoney> {
    const response = await this.getIncomeByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getIncomes without sending the request
   */
  async getIncomesRequestOpts(requestParameters: GetIncomesRequest): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getIncomes().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling getIncomes().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getIncomes().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['page_size'] = requestParameters['pageSize']
    }

    if (requestParameters['sourceOrganization'] != null) {
      queryParameters['source_organization'] = requestParameters['sourceOrganization']
    }

    if (requestParameters['invoiceReference'] != null) {
      queryParameters['invoice_reference'] = requestParameters['invoiceReference']
    }

    if (requestParameters['description'] != null) {
      queryParameters['description'] = requestParameters['description']
    }

    if (requestParameters['amount'] != null) {
      queryParameters['amount'] = requestParameters['amount']
    }

    if (requestParameters['incomeTypeId'] != null) {
      queryParameters['income_type_id'] = requestParameters['incomeTypeId']
    }

    if (requestParameters['moneyReceived'] != null) {
      queryParameters['money_received'] = requestParameters['moneyReceived']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/incomes`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all incomes
   */
  async getIncomesRaw(
    requestParameters: GetIncomesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<IncomeMoney>>> {
    const requestOptions = await this.getIncomesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IncomeMoneyFromJSON))
  }

  /**
   * Get all incomes
   */
  async getIncomes(
    requestParameters: GetIncomesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<IncomeMoney>> {
    const response = await this.getIncomesRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
