/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BadRequestException,
    BadRequestExceptionFromJSON,
    BadRequestExceptionToJSON,
} from '../models/BadRequestException';
import {
    type CrupdateNotification,
    CrupdateNotificationFromJSON,
    CrupdateNotificationToJSON,
} from '../models/CrupdateNotification';
import {
    type InternalServerException,
    InternalServerExceptionFromJSON,
    InternalServerExceptionToJSON,
} from '../models/InternalServerException';
import {
    type NotAuthorizedException,
    NotAuthorizedExceptionFromJSON,
    NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException';
import {
    type Notification,
    NotificationFromJSON,
    NotificationToJSON,
} from '../models/Notification';
import {
    type PaginatedResponse,
    PaginatedResponseFromJSON,
    PaginatedResponseToJSON,
} from '../models/PaginatedResponse';
import {
    type ResourceNotFoundException,
    ResourceNotFoundExceptionFromJSON,
    ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException';
import {
    type TooManyRequestsException,
    TooManyRequestsExceptionFromJSON,
    TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException';
import {
    type UnreadNotificationCountResponse,
    UnreadNotificationCountResponseFromJSON,
    UnreadNotificationCountResponseToJSON,
} from '../models/UnreadNotificationCountResponse';

export interface CrupdateNotificationsRequest {
    userId: string;
    companyId: string;
    crupdateNotification: Array<CrupdateNotification>;
}

export interface DeleteNotificationByIdRequest {
    userId: string;
    companyId: string;
    id: string;
}

export interface GetNotificationByIdRequest {
    userId: string;
    companyId: string;
    id: string;
}

export interface GetNotificationsRequest {
    userId: string;
    companyId: string;
    page?: number;
    pageSize?: number;
    read?: boolean;
    completed?: boolean;
}

export interface GetUnreadNotificationCountRequest {
    userId: string;
    companyId: string;
}

export interface MarkNotificationAsCompletedRequest {
    userId: string;
    companyId: string;
    id: string;
}

export interface MarkNotificationAsReadRequest {
    userId: string;
    companyId: string;
    id: string;
}

/**
 * 
 */
export class NotificationApi extends runtime.BaseAPI {

    /**
     * Creates request options for crupdateNotifications without sending the request
     */
    async crupdateNotificationsRequestOpts(requestParameters: CrupdateNotificationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling crupdateNotifications().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling crupdateNotifications().'
            );
        }

        if (requestParameters['crupdateNotification'] == null) {
            throw new runtime.RequiredError(
                'crupdateNotification',
                'Required parameter "crupdateNotification" was null or undefined when calling crupdateNotifications().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/notifications`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['crupdateNotification']!.map(CrupdateNotificationToJSON),
        };
    }

    /**
     * Create or update notifications
     */
    async crupdateNotificationsRaw(requestParameters: CrupdateNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Notification>>> {
        const requestOptions = await this.crupdateNotificationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationFromJSON));
    }

    /**
     * Create or update notifications
     */
    async crupdateNotifications(requestParameters: CrupdateNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Notification>> {
        const response = await this.crupdateNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteNotificationById without sending the request
     */
    async deleteNotificationByIdRequestOpts(requestParameters: DeleteNotificationByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteNotificationById().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling deleteNotificationById().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteNotificationById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/notifications/{id}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete notification by identifier
     */
    async deleteNotificationByIdRaw(requestParameters: DeleteNotificationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteNotificationByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete notification by identifier
     */
    async deleteNotificationById(requestParameters: DeleteNotificationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteNotificationByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getNotificationById without sending the request
     */
    async getNotificationByIdRequestOpts(requestParameters: GetNotificationByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getNotificationById().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getNotificationById().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getNotificationById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/notifications/{id}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get notification by identifier
     */
    async getNotificationByIdRaw(requestParameters: GetNotificationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Notification>> {
        const requestOptions = await this.getNotificationByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationFromJSON(jsonValue));
    }

    /**
     * Get notification by identifier
     */
    async getNotificationById(requestParameters: GetNotificationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Notification> {
        const response = await this.getNotificationByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNotifications without sending the request
     */
    async getNotificationsRequestOpts(requestParameters: GetNotificationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getNotifications().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getNotifications().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['read'] != null) {
            queryParameters['read'] = requestParameters['read'];
        }

        if (requestParameters['completed'] != null) {
            queryParameters['completed'] = requestParameters['completed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/notifications`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all notifications for the current user
     */
    async getNotificationsRaw(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponse>> {
        const requestOptions = await this.getNotificationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseFromJSON(jsonValue));
    }

    /**
     * Get all notifications for the current user
     */
    async getNotifications(requestParameters: GetNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponse> {
        const response = await this.getNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUnreadNotificationCount without sending the request
     */
    async getUnreadNotificationCountRequestOpts(requestParameters: GetUnreadNotificationCountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUnreadNotificationCount().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getUnreadNotificationCount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/notifications/unread_count`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get unread notification count for the current user
     */
    async getUnreadNotificationCountRaw(requestParameters: GetUnreadNotificationCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnreadNotificationCountResponse>> {
        const requestOptions = await this.getUnreadNotificationCountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnreadNotificationCountResponseFromJSON(jsonValue));
    }

    /**
     * Get unread notification count for the current user
     */
    async getUnreadNotificationCount(requestParameters: GetUnreadNotificationCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnreadNotificationCountResponse> {
        const response = await this.getUnreadNotificationCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markNotificationAsCompleted without sending the request
     */
    async markNotificationAsCompletedRequestOpts(requestParameters: MarkNotificationAsCompletedRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling markNotificationAsCompleted().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling markNotificationAsCompleted().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling markNotificationAsCompleted().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/notifications/{id}/complete`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark notification as completed
     */
    async markNotificationAsCompletedRaw(requestParameters: MarkNotificationAsCompletedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Notification>> {
        const requestOptions = await this.markNotificationAsCompletedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationFromJSON(jsonValue));
    }

    /**
     * Mark notification as completed
     */
    async markNotificationAsCompleted(requestParameters: MarkNotificationAsCompletedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Notification> {
        const response = await this.markNotificationAsCompletedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markNotificationAsRead without sending the request
     */
    async markNotificationAsReadRequestOpts(requestParameters: MarkNotificationAsReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling markNotificationAsRead().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling markNotificationAsRead().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling markNotificationAsRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/notifications/{id}/read`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark notification as read
     */
    async markNotificationAsReadRaw(requestParameters: MarkNotificationAsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Notification>> {
        const requestOptions = await this.markNotificationAsReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationFromJSON(jsonValue));
    }

    /**
     * Mark notification as read
     */
    async markNotificationAsRead(requestParameters: MarkNotificationAsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Notification> {
        const response = await this.markNotificationAsReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
