/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import {
  type CrupdateOrganization,
  CrupdateOrganizationFromJSON,
  CrupdateOrganizationToJSON,
} from '../models/CrupdateOrganization'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import { type Organization, OrganizationFromJSON, OrganizationToJSON } from '../models/Organization'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'

export interface CrupdateOrganizationsRequest {
  userId: string
  companyId: string
  crupdateOrganization: Array<CrupdateOrganization>
}

export interface DeleteOrganizationByIdRequest {
  userId: string
  companyId: string
  id: string
}

export interface GetOrganizationByIdRequest {
  userId: string
  companyId: string
  id: string
}

export interface GetOrganizationsRequest {
  userId: string
  companyId: string
}

/**
 *
 */
export class OrganizationApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateOrganizations without sending the request
   */
  async crupdateOrganizationsRequestOpts(
    requestParameters: CrupdateOrganizationsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling crupdateOrganizations().',
      )
    }

    if (requestParameters['companyId'] == null) {
      throw new runtime.RequiredError(
        'companyId',
        'Required parameter "companyId" was null or undefined when calling crupdateOrganizations().',
      )
    }

    if (requestParameters['crupdateOrganization'] == null) {
      throw new runtime.RequiredError(
        'crupdateOrganization',
        'Required parameter "crupdateOrganization" was null or undefined when calling crupdateOrganizations().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users/{userId}/companies/{companyId}/organizations`
    urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{companyId}',
      encodeURIComponent(String(requestParameters['companyId'])),
    )

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateOrganization']!.map(CrupdateOrganizationToJSON),
    }
  }

  /**
   * Create or update organizations (crupdate)
   */
  async crupdateOrganizationsRaw(
    requestParameters: CrupdateOrganizationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Organization>>> {
    const requestOptions = await this.crupdateOrganizationsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationFromJSON))
  }

  /**
   * Create or update organizations (crupdate)
   */
  async crupdateOrganizations(
    requestParameters: CrupdateOrganizationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Organization>> {
    const response = await this.crupdateOrganizationsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteOrganizationById without sending the request
   */
  async deleteOrganizationByIdRequestOpts(
    requestParameters: DeleteOrganizationByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling deleteOrganizationById().',
      )
    }

    if (requestParameters['companyId'] == null) {
      throw new runtime.RequiredError(
        'companyId',
        'Required parameter "companyId" was null or undefined when calling deleteOrganizationById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteOrganizationById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users/{userId}/companies/{companyId}/organizations/{id}`
    urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{companyId}',
      encodeURIComponent(String(requestParameters['companyId'])),
    )
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete an organization
   */
  async deleteOrganizationByIdRaw(
    requestParameters: DeleteOrganizationByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteOrganizationByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete an organization
   */
  async deleteOrganizationById(
    requestParameters: DeleteOrganizationByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteOrganizationByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getOrganizationById without sending the request
   */
  async getOrganizationByIdRequestOpts(
    requestParameters: GetOrganizationByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getOrganizationById().',
      )
    }

    if (requestParameters['companyId'] == null) {
      throw new runtime.RequiredError(
        'companyId',
        'Required parameter "companyId" was null or undefined when calling getOrganizationById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getOrganizationById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users/{userId}/companies/{companyId}/organizations/{id}`
    urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{companyId}',
      encodeURIComponent(String(requestParameters['companyId'])),
    )
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get organization by ID
   */
  async getOrganizationByIdRaw(
    requestParameters: GetOrganizationByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Organization>> {
    const requestOptions = await this.getOrganizationByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue))
  }

  /**
   * Get organization by ID
   */
  async getOrganizationById(
    requestParameters: GetOrganizationByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Organization> {
    const response = await this.getOrganizationByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getOrganizations without sending the request
   */
  async getOrganizationsRequestOpts(
    requestParameters: GetOrganizationsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getOrganizations().',
      )
    }

    if (requestParameters['companyId'] == null) {
      throw new runtime.RequiredError(
        'companyId',
        'Required parameter "companyId" was null or undefined when calling getOrganizations().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/users/{userId}/companies/{companyId}/organizations`
    urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{companyId}',
      encodeURIComponent(String(requestParameters['companyId'])),
    )

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all organizations for a company
   */
  async getOrganizationsRaw(
    requestParameters: GetOrganizationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Organization>>> {
    const requestOptions = await this.getOrganizationsRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationFromJSON))
  }

  /**
   * Get all organizations for a company
   */
  async getOrganizations(
    requestParameters: GetOrganizationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Organization>> {
    const response = await this.getOrganizationsRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
