/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BadRequestException,
    BadRequestExceptionFromJSON,
    BadRequestExceptionToJSON,
} from '../models/BadRequestException';
import {
    type EquipmentBreakdownResponse,
    EquipmentBreakdownResponseFromJSON,
    EquipmentBreakdownResponseToJSON,
} from '../models/EquipmentBreakdownResponse';
import {
    type EquipmentDashboardResponse,
    EquipmentDashboardResponseFromJSON,
    EquipmentDashboardResponseToJSON,
} from '../models/EquipmentDashboardResponse';
import {
    type EquipmentSummaryResponse,
    EquipmentSummaryResponseFromJSON,
    EquipmentSummaryResponseToJSON,
} from '../models/EquipmentSummaryResponse';
import {
    type HrBreakdownResponse,
    HrBreakdownResponseFromJSON,
    HrBreakdownResponseToJSON,
} from '../models/HrBreakdownResponse';
import {
    type HrDashboardResponse,
    HrDashboardResponseFromJSON,
    HrDashboardResponseToJSON,
} from '../models/HrDashboardResponse';
import {
    type HrSummaryResponse,
    HrSummaryResponseFromJSON,
    HrSummaryResponseToJSON,
} from '../models/HrSummaryResponse';
import {
    type InternalServerException,
    InternalServerExceptionFromJSON,
    InternalServerExceptionToJSON,
} from '../models/InternalServerException';
import {
    type MaterialBreakdownResponse,
    MaterialBreakdownResponseFromJSON,
    MaterialBreakdownResponseToJSON,
} from '../models/MaterialBreakdownResponse';
import {
    type MaterialDashboardResponse,
    MaterialDashboardResponseFromJSON,
    MaterialDashboardResponseToJSON,
} from '../models/MaterialDashboardResponse';
import {
    type MaterialSummaryResponse,
    MaterialSummaryResponseFromJSON,
    MaterialSummaryResponseToJSON,
} from '../models/MaterialSummaryResponse';
import {
    type MonetaryBreakdownResponse,
    MonetaryBreakdownResponseFromJSON,
    MonetaryBreakdownResponseToJSON,
} from '../models/MonetaryBreakdownResponse';
import {
    type MonetaryDashboardResponse,
    MonetaryDashboardResponseFromJSON,
    MonetaryDashboardResponseToJSON,
} from '../models/MonetaryDashboardResponse';
import {
    type MonetarySummaryResponse,
    MonetarySummaryResponseFromJSON,
    MonetarySummaryResponseToJSON,
} from '../models/MonetarySummaryResponse';
import {
    type NotAuthorizedException,
    NotAuthorizedExceptionFromJSON,
    NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException';
import {
    type ResourceNotFoundException,
    ResourceNotFoundExceptionFromJSON,
    ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException';
import {
    type TimeSeriesResponse,
    TimeSeriesResponseFromJSON,
    TimeSeriesResponseToJSON,
} from '../models/TimeSeriesResponse';
import {
    type TooManyRequestsException,
    TooManyRequestsExceptionFromJSON,
    TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException';
import {
    type YearlyReport,
    YearlyReportFromJSON,
    YearlyReportToJSON,
} from '../models/YearlyReport';

export interface GetBudgetTimeSeriesRequest {
    userId: string;
    companyId: string;
    dateFrom?: Date;
    dateTo?: Date;
    granularity?: string;
}

export interface GetCashFlowTimeSeriesRequest {
    userId: string;
    companyId: string;
    dateFrom?: Date;
    dateTo?: Date;
    granularity?: string;
}

export interface GetEquipmentDashboardRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetEquipmentDashboardBreakdownRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetEquipmentDashboardSummaryRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetExpenseBreakdownTimeSeriesRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
    granularity?: string;
}

export interface GetExpensesTimeSeriesRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
    granularity?: string;
}

export interface GetHrDashboardRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetHrDashboardBreakdownRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetHrDashboardSummaryRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetMaterialDashboardRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetMaterialDashboardBreakdownRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetMaterialDashboardSummaryRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetMonetaryDashboardRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetMonetaryDashboardBreakdownRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetMonetaryDashboardSummaryRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
}

export interface GetProfitTimeSeriesRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
    granularity?: string;
}

export interface GetReceivablesTimeSeriesRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
    granularity?: string;
}

export interface GetRevenueTimeSeriesRequest {
    userId: string;
    companyId: string;
    jobId?: string;
    dateFrom?: Date;
    dateTo?: Date;
    granularity?: string;
}

export interface UsersUserIdCompaniesCompanyIdYearlyReportGetRequest {
    userId: string;
    companyId: string;
    year: number;
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class ReportApi extends runtime.BaseAPI {

    /**
     * Creates request options for getBudgetTimeSeries without sending the request
     */
    async getBudgetTimeSeriesRequestOpts(requestParameters: GetBudgetTimeSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getBudgetTimeSeries().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getBudgetTimeSeries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/budget`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get budget time series
     */
    async getBudgetTimeSeriesRaw(requestParameters: GetBudgetTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSeriesResponse>> {
        const requestOptions = await this.getBudgetTimeSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Get budget time series
     */
    async getBudgetTimeSeries(requestParameters: GetBudgetTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSeriesResponse> {
        const response = await this.getBudgetTimeSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCashFlowTimeSeries without sending the request
     */
    async getCashFlowTimeSeriesRequestOpts(requestParameters: GetCashFlowTimeSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getCashFlowTimeSeries().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getCashFlowTimeSeries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/cashflow`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get cash flow time series
     */
    async getCashFlowTimeSeriesRaw(requestParameters: GetCashFlowTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSeriesResponse>> {
        const requestOptions = await this.getCashFlowTimeSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Get cash flow time series
     */
    async getCashFlowTimeSeries(requestParameters: GetCashFlowTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSeriesResponse> {
        const response = await this.getCashFlowTimeSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEquipmentDashboard without sending the request
     */
    async getEquipmentDashboardRequestOpts(requestParameters: GetEquipmentDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getEquipmentDashboard().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getEquipmentDashboard().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/equipment`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get equipment dashboard
     */
    async getEquipmentDashboardRaw(requestParameters: GetEquipmentDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentDashboardResponse>> {
        const requestOptions = await this.getEquipmentDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentDashboardResponseFromJSON(jsonValue));
    }

    /**
     * Get equipment dashboard
     */
    async getEquipmentDashboard(requestParameters: GetEquipmentDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentDashboardResponse> {
        const response = await this.getEquipmentDashboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEquipmentDashboardBreakdown without sending the request
     */
    async getEquipmentDashboardBreakdownRequestOpts(requestParameters: GetEquipmentDashboardBreakdownRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getEquipmentDashboardBreakdown().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getEquipmentDashboardBreakdown().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/equipment/breakdown`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get equipment dashboard breakdown
     */
    async getEquipmentDashboardBreakdownRaw(requestParameters: GetEquipmentDashboardBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentBreakdownResponse>> {
        const requestOptions = await this.getEquipmentDashboardBreakdownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentBreakdownResponseFromJSON(jsonValue));
    }

    /**
     * Get equipment dashboard breakdown
     */
    async getEquipmentDashboardBreakdown(requestParameters: GetEquipmentDashboardBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentBreakdownResponse> {
        const response = await this.getEquipmentDashboardBreakdownRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEquipmentDashboardSummary without sending the request
     */
    async getEquipmentDashboardSummaryRequestOpts(requestParameters: GetEquipmentDashboardSummaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getEquipmentDashboardSummary().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getEquipmentDashboardSummary().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/equipment/summary`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get equipment dashboard summary
     */
    async getEquipmentDashboardSummaryRaw(requestParameters: GetEquipmentDashboardSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentSummaryResponse>> {
        const requestOptions = await this.getEquipmentDashboardSummaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentSummaryResponseFromJSON(jsonValue));
    }

    /**
     * Get equipment dashboard summary
     */
    async getEquipmentDashboardSummary(requestParameters: GetEquipmentDashboardSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentSummaryResponse> {
        const response = await this.getEquipmentDashboardSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExpenseBreakdownTimeSeries without sending the request
     */
    async getExpenseBreakdownTimeSeriesRequestOpts(requestParameters: GetExpenseBreakdownTimeSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getExpenseBreakdownTimeSeries().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getExpenseBreakdownTimeSeries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/expense_breakdown`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get expense breakdown time series
     */
    async getExpenseBreakdownTimeSeriesRaw(requestParameters: GetExpenseBreakdownTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSeriesResponse>> {
        const requestOptions = await this.getExpenseBreakdownTimeSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Get expense breakdown time series
     */
    async getExpenseBreakdownTimeSeries(requestParameters: GetExpenseBreakdownTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSeriesResponse> {
        const response = await this.getExpenseBreakdownTimeSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getExpensesTimeSeries without sending the request
     */
    async getExpensesTimeSeriesRequestOpts(requestParameters: GetExpensesTimeSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getExpensesTimeSeries().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getExpensesTimeSeries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/expenses`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get expenses time series
     */
    async getExpensesTimeSeriesRaw(requestParameters: GetExpensesTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSeriesResponse>> {
        const requestOptions = await this.getExpensesTimeSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Get expenses time series
     */
    async getExpensesTimeSeries(requestParameters: GetExpensesTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSeriesResponse> {
        const response = await this.getExpensesTimeSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHrDashboard without sending the request
     */
    async getHrDashboardRequestOpts(requestParameters: GetHrDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getHrDashboard().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getHrDashboard().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/hr`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get HR dashboard
     */
    async getHrDashboardRaw(requestParameters: GetHrDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HrDashboardResponse>> {
        const requestOptions = await this.getHrDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HrDashboardResponseFromJSON(jsonValue));
    }

    /**
     * Get HR dashboard
     */
    async getHrDashboard(requestParameters: GetHrDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HrDashboardResponse> {
        const response = await this.getHrDashboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHrDashboardBreakdown without sending the request
     */
    async getHrDashboardBreakdownRequestOpts(requestParameters: GetHrDashboardBreakdownRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getHrDashboardBreakdown().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getHrDashboardBreakdown().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/hr/breakdown`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get HR dashboard breakdown
     */
    async getHrDashboardBreakdownRaw(requestParameters: GetHrDashboardBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HrBreakdownResponse>> {
        const requestOptions = await this.getHrDashboardBreakdownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HrBreakdownResponseFromJSON(jsonValue));
    }

    /**
     * Get HR dashboard breakdown
     */
    async getHrDashboardBreakdown(requestParameters: GetHrDashboardBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HrBreakdownResponse> {
        const response = await this.getHrDashboardBreakdownRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHrDashboardSummary without sending the request
     */
    async getHrDashboardSummaryRequestOpts(requestParameters: GetHrDashboardSummaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getHrDashboardSummary().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getHrDashboardSummary().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/hr/summary`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get HR dashboard summary
     */
    async getHrDashboardSummaryRaw(requestParameters: GetHrDashboardSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HrSummaryResponse>> {
        const requestOptions = await this.getHrDashboardSummaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HrSummaryResponseFromJSON(jsonValue));
    }

    /**
     * Get HR dashboard summary
     */
    async getHrDashboardSummary(requestParameters: GetHrDashboardSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HrSummaryResponse> {
        const response = await this.getHrDashboardSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMaterialDashboard without sending the request
     */
    async getMaterialDashboardRequestOpts(requestParameters: GetMaterialDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getMaterialDashboard().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getMaterialDashboard().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/materials`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get material dashboard
     */
    async getMaterialDashboardRaw(requestParameters: GetMaterialDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaterialDashboardResponse>> {
        const requestOptions = await this.getMaterialDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaterialDashboardResponseFromJSON(jsonValue));
    }

    /**
     * Get material dashboard
     */
    async getMaterialDashboard(requestParameters: GetMaterialDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaterialDashboardResponse> {
        const response = await this.getMaterialDashboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMaterialDashboardBreakdown without sending the request
     */
    async getMaterialDashboardBreakdownRequestOpts(requestParameters: GetMaterialDashboardBreakdownRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getMaterialDashboardBreakdown().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getMaterialDashboardBreakdown().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/materials/breakdown`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get material dashboard breakdown
     */
    async getMaterialDashboardBreakdownRaw(requestParameters: GetMaterialDashboardBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaterialBreakdownResponse>> {
        const requestOptions = await this.getMaterialDashboardBreakdownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaterialBreakdownResponseFromJSON(jsonValue));
    }

    /**
     * Get material dashboard breakdown
     */
    async getMaterialDashboardBreakdown(requestParameters: GetMaterialDashboardBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaterialBreakdownResponse> {
        const response = await this.getMaterialDashboardBreakdownRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMaterialDashboardSummary without sending the request
     */
    async getMaterialDashboardSummaryRequestOpts(requestParameters: GetMaterialDashboardSummaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getMaterialDashboardSummary().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getMaterialDashboardSummary().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/materials/summary`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get material dashboard summary
     */
    async getMaterialDashboardSummaryRaw(requestParameters: GetMaterialDashboardSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MaterialSummaryResponse>> {
        const requestOptions = await this.getMaterialDashboardSummaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaterialSummaryResponseFromJSON(jsonValue));
    }

    /**
     * Get material dashboard summary
     */
    async getMaterialDashboardSummary(requestParameters: GetMaterialDashboardSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MaterialSummaryResponse> {
        const response = await this.getMaterialDashboardSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMonetaryDashboard without sending the request
     */
    async getMonetaryDashboardRequestOpts(requestParameters: GetMonetaryDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getMonetaryDashboard().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getMonetaryDashboard().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get monetary dashboard
     */
    async getMonetaryDashboardRaw(requestParameters: GetMonetaryDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonetaryDashboardResponse>> {
        const requestOptions = await this.getMonetaryDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonetaryDashboardResponseFromJSON(jsonValue));
    }

    /**
     * Get monetary dashboard
     */
    async getMonetaryDashboard(requestParameters: GetMonetaryDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonetaryDashboardResponse> {
        const response = await this.getMonetaryDashboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMonetaryDashboardBreakdown without sending the request
     */
    async getMonetaryDashboardBreakdownRequestOpts(requestParameters: GetMonetaryDashboardBreakdownRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getMonetaryDashboardBreakdown().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getMonetaryDashboardBreakdown().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/breakdown`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get monetary dashboard breakdown
     */
    async getMonetaryDashboardBreakdownRaw(requestParameters: GetMonetaryDashboardBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonetaryBreakdownResponse>> {
        const requestOptions = await this.getMonetaryDashboardBreakdownRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonetaryBreakdownResponseFromJSON(jsonValue));
    }

    /**
     * Get monetary dashboard breakdown
     */
    async getMonetaryDashboardBreakdown(requestParameters: GetMonetaryDashboardBreakdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonetaryBreakdownResponse> {
        const response = await this.getMonetaryDashboardBreakdownRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMonetaryDashboardSummary without sending the request
     */
    async getMonetaryDashboardSummaryRequestOpts(requestParameters: GetMonetaryDashboardSummaryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getMonetaryDashboardSummary().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getMonetaryDashboardSummary().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/summary`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get monetary dashboard summary
     */
    async getMonetaryDashboardSummaryRaw(requestParameters: GetMonetaryDashboardSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MonetarySummaryResponse>> {
        const requestOptions = await this.getMonetaryDashboardSummaryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonetarySummaryResponseFromJSON(jsonValue));
    }

    /**
     * Get monetary dashboard summary
     */
    async getMonetaryDashboardSummary(requestParameters: GetMonetaryDashboardSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MonetarySummaryResponse> {
        const response = await this.getMonetaryDashboardSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProfitTimeSeries without sending the request
     */
    async getProfitTimeSeriesRequestOpts(requestParameters: GetProfitTimeSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getProfitTimeSeries().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getProfitTimeSeries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/profit`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get profit time series
     */
    async getProfitTimeSeriesRaw(requestParameters: GetProfitTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSeriesResponse>> {
        const requestOptions = await this.getProfitTimeSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Get profit time series
     */
    async getProfitTimeSeries(requestParameters: GetProfitTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSeriesResponse> {
        const response = await this.getProfitTimeSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReceivablesTimeSeries without sending the request
     */
    async getReceivablesTimeSeriesRequestOpts(requestParameters: GetReceivablesTimeSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getReceivablesTimeSeries().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getReceivablesTimeSeries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/receivables`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get receivables time series
     */
    async getReceivablesTimeSeriesRaw(requestParameters: GetReceivablesTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSeriesResponse>> {
        const requestOptions = await this.getReceivablesTimeSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Get receivables time series
     */
    async getReceivablesTimeSeries(requestParameters: GetReceivablesTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSeriesResponse> {
        const response = await this.getReceivablesTimeSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRevenueTimeSeries without sending the request
     */
    async getRevenueTimeSeriesRequestOpts(requestParameters: GetRevenueTimeSeriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getRevenueTimeSeries().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getRevenueTimeSeries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/dashboard/monetary/revenue`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get revenue time series
     */
    async getRevenueTimeSeriesRaw(requestParameters: GetRevenueTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSeriesResponse>> {
        const requestOptions = await this.getRevenueTimeSeriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Get revenue time series
     */
    async getRevenueTimeSeries(requestParameters: GetRevenueTimeSeriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSeriesResponse> {
        const response = await this.getRevenueTimeSeriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersUserIdCompaniesCompanyIdYearlyReportGet without sending the request
     */
    async usersUserIdCompaniesCompanyIdYearlyReportGetRequestOpts(requestParameters: UsersUserIdCompaniesCompanyIdYearlyReportGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling usersUserIdCompaniesCompanyIdYearlyReportGet().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling usersUserIdCompaniesCompanyIdYearlyReportGet().'
            );
        }

        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling usersUserIdCompaniesCompanyIdYearlyReportGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/companies/{companyId}/yearly_report`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace('{companyId}', encodeURIComponent(String(requestParameters['companyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all jobs for the specified year with their income/expense details, including ongoing (IN_PROGRESS) jobs
     * Get yearly report with job financials
     */
    async usersUserIdCompaniesCompanyIdYearlyReportGetRaw(requestParameters: UsersUserIdCompaniesCompanyIdYearlyReportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<YearlyReport>> {
        const requestOptions = await this.usersUserIdCompaniesCompanyIdYearlyReportGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => YearlyReportFromJSON(jsonValue));
    }

    /**
     * Returns all jobs for the specified year with their income/expense details, including ongoing (IN_PROGRESS) jobs
     * Get yearly report with job financials
     */
    async usersUserIdCompaniesCompanyIdYearlyReportGet(requestParameters: UsersUserIdCompaniesCompanyIdYearlyReportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<YearlyReport> {
        const response = await this.usersUserIdCompaniesCompanyIdYearlyReportGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
