/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import {
  type CrupdateTravelExpense,
  CrupdateTravelExpenseFromJSON,
  CrupdateTravelExpenseToJSON,
} from '../models/CrupdateTravelExpense'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'
import {
  type TravelExpense,
  TravelExpenseFromJSON,
  TravelExpenseToJSON,
} from '../models/TravelExpense'

export interface CrupdateTravelExpensesRequest {
  compId: string
  jobId: string
  userId: string
  expensesId: string
  crupdateTravelExpense: Array<CrupdateTravelExpense>
}

export interface DeleteTravelExpenseByIdRequest {
  compId: string
  jobId: string
  userId: string
  expensesId: string
  id: string
}

export interface GetTravelExpenseByIdRequest {
  compId: string
  jobId: string
  userId: string
  expensesId: string
  id: string
}

export interface GetTravelExpensesRequest {
  compId: string
  jobId: string
  userId: string
  expensesId: string
  page?: number
  pageSize?: number
  expenseId?: string
  departureLocation?: string
  arrivalLocation?: string
}

/**
 *
 */
export class TravelExpenseApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateTravelExpenses without sending the request
   */
  async crupdateTravelExpensesRequestOpts(
    requestParameters: CrupdateTravelExpensesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateTravelExpenses().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling crupdateTravelExpenses().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling crupdateTravelExpenses().',
      )
    }

    if (requestParameters['expensesId'] == null) {
      throw new runtime.RequiredError(
        'expensesId',
        'Required parameter "expensesId" was null or undefined when calling crupdateTravelExpenses().',
      )
    }

    if (requestParameters['crupdateTravelExpense'] == null) {
      throw new runtime.RequiredError(
        'crupdateTravelExpense',
        'Required parameter "crupdateTravelExpense" was null or undefined when calling crupdateTravelExpenses().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/travel_expenses`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{expenses_id}',
      encodeURIComponent(String(requestParameters['expensesId'])),
    )

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateTravelExpense']!.map(CrupdateTravelExpenseToJSON),
    }
  }

  /**
   * Create new travel expenses or update existing ones
   */
  async crupdateTravelExpensesRaw(
    requestParameters: CrupdateTravelExpensesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TravelExpense>>> {
    const requestOptions = await this.crupdateTravelExpensesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TravelExpenseFromJSON),
    )
  }

  /**
   * Create new travel expenses or update existing ones
   */
  async crupdateTravelExpenses(
    requestParameters: CrupdateTravelExpensesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TravelExpense>> {
    const response = await this.crupdateTravelExpensesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteTravelExpenseById without sending the request
   */
  async deleteTravelExpenseByIdRequestOpts(
    requestParameters: DeleteTravelExpenseByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling deleteTravelExpenseById().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling deleteTravelExpenseById().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling deleteTravelExpenseById().',
      )
    }

    if (requestParameters['expensesId'] == null) {
      throw new runtime.RequiredError(
        'expensesId',
        'Required parameter "expensesId" was null or undefined when calling deleteTravelExpenseById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteTravelExpenseById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/travel_expenses/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{expenses_id}',
      encodeURIComponent(String(requestParameters['expensesId'])),
    )
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete travel expense by identifier
   */
  async deleteTravelExpenseByIdRaw(
    requestParameters: DeleteTravelExpenseByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteTravelExpenseByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete travel expense by identifier
   */
  async deleteTravelExpenseById(
    requestParameters: DeleteTravelExpenseByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteTravelExpenseByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getTravelExpenseById without sending the request
   */
  async getTravelExpenseByIdRequestOpts(
    requestParameters: GetTravelExpenseByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getTravelExpenseById().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling getTravelExpenseById().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getTravelExpenseById().',
      )
    }

    if (requestParameters['expensesId'] == null) {
      throw new runtime.RequiredError(
        'expensesId',
        'Required parameter "expensesId" was null or undefined when calling getTravelExpenseById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getTravelExpenseById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/travel_expenses/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{expenses_id}',
      encodeURIComponent(String(requestParameters['expensesId'])),
    )
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get travel expense by identifier
   */
  async getTravelExpenseByIdRaw(
    requestParameters: GetTravelExpenseByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TravelExpense>> {
    const requestOptions = await this.getTravelExpenseByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => TravelExpenseFromJSON(jsonValue))
  }

  /**
   * Get travel expense by identifier
   */
  async getTravelExpenseById(
    requestParameters: GetTravelExpenseByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TravelExpense> {
    const response = await this.getTravelExpenseByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getTravelExpenses without sending the request
   */
  async getTravelExpensesRequestOpts(
    requestParameters: GetTravelExpensesRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getTravelExpenses().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling getTravelExpenses().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getTravelExpenses().',
      )
    }

    if (requestParameters['expensesId'] == null) {
      throw new runtime.RequiredError(
        'expensesId',
        'Required parameter "expensesId" was null or undefined when calling getTravelExpenses().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['page_size'] = requestParameters['pageSize']
    }

    if (requestParameters['expenseId'] != null) {
      queryParameters['expense_id'] = requestParameters['expenseId']
    }

    if (requestParameters['departureLocation'] != null) {
      queryParameters['departure_location'] = requestParameters['departureLocation']
    }

    if (requestParameters['arrivalLocation'] != null) {
      queryParameters['arrival_location'] = requestParameters['arrivalLocation']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/travel_expenses`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{expenses_id}',
      encodeURIComponent(String(requestParameters['expensesId'])),
    )

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all travel expenses
   */
  async getTravelExpensesRaw(
    requestParameters: GetTravelExpensesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TravelExpense>>> {
    const requestOptions = await this.getTravelExpensesRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TravelExpenseFromJSON),
    )
  }

  /**
   * Get all travel expenses
   */
  async getTravelExpenses(
    requestParameters: GetTravelExpensesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TravelExpense>> {
    const response = await this.getTravelExpensesRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
