/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  type BadRequestException,
  BadRequestExceptionFromJSON,
  BadRequestExceptionToJSON,
} from '../models/BadRequestException'
import {
  type CrupdateTravelEquipment,
  CrupdateTravelEquipmentFromJSON,
  CrupdateTravelEquipmentToJSON,
} from '../models/CrupdateTravelEquipment'
import {
  type InternalServerException,
  InternalServerExceptionFromJSON,
  InternalServerExceptionToJSON,
} from '../models/InternalServerException'
import {
  type NotAuthorizedException,
  NotAuthorizedExceptionFromJSON,
  NotAuthorizedExceptionToJSON,
} from '../models/NotAuthorizedException'
import {
  type ResourceNotFoundException,
  ResourceNotFoundExceptionFromJSON,
  ResourceNotFoundExceptionToJSON,
} from '../models/ResourceNotFoundException'
import {
  type TooManyRequestsException,
  TooManyRequestsExceptionFromJSON,
  TooManyRequestsExceptionToJSON,
} from '../models/TooManyRequestsException'
import {
  type TransportStatus,
  TransportStatusFromJSON,
  TransportStatusToJSON,
} from '../models/TransportStatus'
import {
  type TravelEquipment,
  TravelEquipmentFromJSON,
  TravelEquipmentToJSON,
} from '../models/TravelEquipment'

export interface CrupdateTravelEquipmentRequest {
  compId: string
  jobId: string
  userId: string
  travelExpensesId: string
  crupdateTravelEquipment: Array<CrupdateTravelEquipment>
}

export interface DeleteTravelEquipmentByIdRequest {
  compId: string
  jobId: string
  userId: string
  travelExpensesId: string
  id: string
}

export interface GetTravelEquipmentRequest {
  compId: string
  jobId: string
  userId: string
  travelExpensesId: string
  page?: number
  pageSize?: number
  travelId?: string
  equipmentId?: string
  quantity?: number
  status?: TransportStatus
  arrivalLocation?: string
  arrivalDateMin?: Date
  arrivalDateMax?: Date
  notArrived?: boolean
}

export interface GetTravelEquipmentByIdRequest {
  compId: string
  jobId: string
  userId: string
  travelExpensesId: string
  id: string
}

/**
 *
 */
export class TravelEquipmentApi extends runtime.BaseAPI {
  /**
   * Creates request options for crupdateTravelEquipment without sending the request
   */
  async crupdateTravelEquipmentRequestOpts(
    requestParameters: CrupdateTravelEquipmentRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling crupdateTravelEquipment().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling crupdateTravelEquipment().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling crupdateTravelEquipment().',
      )
    }

    if (requestParameters['travelExpensesId'] == null) {
      throw new runtime.RequiredError(
        'travelExpensesId',
        'Required parameter "travelExpensesId" was null or undefined when calling crupdateTravelEquipment().',
      )
    }

    if (requestParameters['crupdateTravelEquipment'] == null) {
      throw new runtime.RequiredError(
        'crupdateTravelEquipment',
        'Required parameter "crupdateTravelEquipment" was null or undefined when calling crupdateTravelEquipment().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/travel_expenses/{travel_expenses_id}/travel_equipment`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{travel_expenses_id}',
      encodeURIComponent(String(requestParameters['travelExpensesId'])),
    )

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters['crupdateTravelEquipment']!.map(CrupdateTravelEquipmentToJSON),
    }
  }

  /**
   * Create new travel equipment or update existing ones
   */
  async crupdateTravelEquipmentRaw(
    requestParameters: CrupdateTravelEquipmentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TravelEquipment>>> {
    const requestOptions = await this.crupdateTravelEquipmentRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TravelEquipmentFromJSON),
    )
  }

  /**
   * Create new travel equipment or update existing ones
   */
  async crupdateTravelEquipment(
    requestParameters: CrupdateTravelEquipmentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TravelEquipment>> {
    const response = await this.crupdateTravelEquipmentRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for deleteTravelEquipmentById without sending the request
   */
  async deleteTravelEquipmentByIdRequestOpts(
    requestParameters: DeleteTravelEquipmentByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling deleteTravelEquipmentById().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling deleteTravelEquipmentById().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling deleteTravelEquipmentById().',
      )
    }

    if (requestParameters['travelExpensesId'] == null) {
      throw new runtime.RequiredError(
        'travelExpensesId',
        'Required parameter "travelExpensesId" was null or undefined when calling deleteTravelEquipmentById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteTravelEquipmentById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/travel_expenses/{travel_expenses_id}/travel_equipment/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{travel_expenses_id}',
      encodeURIComponent(String(requestParameters['travelExpensesId'])),
    )
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Delete travel equipment by identifier
   */
  async deleteTravelEquipmentByIdRaw(
    requestParameters: DeleteTravelEquipmentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteTravelEquipmentByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete travel equipment by identifier
   */
  async deleteTravelEquipmentById(
    requestParameters: DeleteTravelEquipmentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteTravelEquipmentByIdRaw(requestParameters, initOverrides)
  }

  /**
   * Creates request options for getTravelEquipment without sending the request
   */
  async getTravelEquipmentRequestOpts(
    requestParameters: GetTravelEquipmentRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getTravelEquipment().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling getTravelEquipment().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getTravelEquipment().',
      )
    }

    if (requestParameters['travelExpensesId'] == null) {
      throw new runtime.RequiredError(
        'travelExpensesId',
        'Required parameter "travelExpensesId" was null or undefined when calling getTravelEquipment().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page']
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['page_size'] = requestParameters['pageSize']
    }

    if (requestParameters['travelId'] != null) {
      queryParameters['travel_id'] = requestParameters['travelId']
    }

    if (requestParameters['equipmentId'] != null) {
      queryParameters['equipment_id'] = requestParameters['equipmentId']
    }

    if (requestParameters['quantity'] != null) {
      queryParameters['quantity'] = requestParameters['quantity']
    }

    if (requestParameters['status'] != null) {
      queryParameters['status'] = requestParameters['status']
    }

    if (requestParameters['arrivalLocation'] != null) {
      queryParameters['arrival_location'] = requestParameters['arrivalLocation']
    }

    if (requestParameters['arrivalDateMin'] != null) {
      queryParameters['arrival_date_min'] = (
        requestParameters['arrivalDateMin'] as any
      ).toISOString()
    }

    if (requestParameters['arrivalDateMax'] != null) {
      queryParameters['arrival_date_max'] = (
        requestParameters['arrivalDateMax'] as any
      ).toISOString()
    }

    if (requestParameters['notArrived'] != null) {
      queryParameters['not_arrived'] = requestParameters['notArrived']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/travel_expenses/{travel_expenses_id}/travel_equipment`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{travel_expenses_id}',
      encodeURIComponent(String(requestParameters['travelExpensesId'])),
    )

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get all travel equipment
   */
  async getTravelEquipmentRaw(
    requestParameters: GetTravelEquipmentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TravelEquipment>>> {
    const requestOptions = await this.getTravelEquipmentRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TravelEquipmentFromJSON),
    )
  }

  /**
   * Get all travel equipment
   */
  async getTravelEquipment(
    requestParameters: GetTravelEquipmentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TravelEquipment>> {
    const response = await this.getTravelEquipmentRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Creates request options for getTravelEquipmentById without sending the request
   */
  async getTravelEquipmentByIdRequestOpts(
    requestParameters: GetTravelEquipmentByIdRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['compId'] == null) {
      throw new runtime.RequiredError(
        'compId',
        'Required parameter "compId" was null or undefined when calling getTravelEquipmentById().',
      )
    }

    if (requestParameters['jobId'] == null) {
      throw new runtime.RequiredError(
        'jobId',
        'Required parameter "jobId" was null or undefined when calling getTravelEquipmentById().',
      )
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getTravelEquipmentById().',
      )
    }

    if (requestParameters['travelExpensesId'] == null) {
      throw new runtime.RequiredError(
        'travelExpensesId',
        'Required parameter "travelExpensesId" was null or undefined when calling getTravelEquipmentById().',
      )
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getTravelEquipmentById().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/companies/{comp_id}/job/{job_id}/user/{user_id}/travel_expenses/{travel_expenses_id}/travel_equipment/{id}`
    urlPath = urlPath.replace('{comp_id}', encodeURIComponent(String(requestParameters['compId'])))
    urlPath = urlPath.replace('{job_id}', encodeURIComponent(String(requestParameters['jobId'])))
    urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])))
    urlPath = urlPath.replace(
      '{travel_expenses_id}',
      encodeURIComponent(String(requestParameters['travelExpensesId'])),
    )
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])))

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    }
  }

  /**
   * Get travel equipment by identifier
   */
  async getTravelEquipmentByIdRaw(
    requestParameters: GetTravelEquipmentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TravelEquipment>> {
    const requestOptions = await this.getTravelEquipmentByIdRequestOpts(requestParameters)
    const response = await this.request(requestOptions, initOverrides)

    return new runtime.JSONApiResponse(response, (jsonValue) => TravelEquipmentFromJSON(jsonValue))
  }

  /**
   * Get travel equipment by identifier
   */
  async getTravelEquipmentById(
    requestParameters: GetTravelEquipmentByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TravelEquipment> {
    const response = await this.getTravelEquipmentByIdRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
