/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'
import type { CashTransactionType } from './CashTransactionType'
import {
  CashTransactionTypeFromJSON,
  CashTransactionTypeFromJSONTyped,
  CashTransactionTypeToJSON,
  CashTransactionTypeToJSONTyped,
} from './CashTransactionType'

/**
 *
 * @export
 * @interface CashTransaction
 */
export interface CashTransaction {
  /**
   *
   * @type {string}
   * @memberof CashTransaction
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof CashTransaction
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof CashTransaction
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof CashTransaction
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof CashTransaction
   */
  updated_by?: AuditUser
  /**
   *
   * @type {string}
   * @memberof CashTransaction
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CashTransaction
   */
  cash_account_id?: string
  /**
   *
   * @type {number}
   * @memberof CashTransaction
   */
  amount?: number
  /**
   *
   * @type {Date}
   * @memberof CashTransaction
   */
  transaction_date?: Date
  /**
   *
   * @type {string}
   * @memberof CashTransaction
   */
  description?: string
  /**
   *
   * @type {CashTransactionType}
   * @memberof CashTransaction
   */
  type?: CashTransactionType
}

/**
 * Check if a given object implements the CashTransaction interface.
 */
export function instanceOfCashTransaction(value: object): value is CashTransaction {
  return true
}

export function CashTransactionFromJSON(json: any): CashTransaction {
  return CashTransactionFromJSONTyped(json, false)
}

export function CashTransactionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CashTransaction {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    id: json['id'] == null ? undefined : json['id'],
    cash_account_id: json['cash_account_id'] == null ? undefined : json['cash_account_id'],
    amount: json['amount'] == null ? undefined : json['amount'],
    transaction_date:
      json['transaction_date'] == null ? undefined : new Date(json['transaction_date']),
    description: json['description'] == null ? undefined : json['description'],
    type: json['type'] == null ? undefined : CashTransactionTypeFromJSON(json['type']),
  }
}

export function CashTransactionToJSON(json: any): CashTransaction {
  return CashTransactionToJSONTyped(json, false)
}

export function CashTransactionToJSONTyped(
  value?: CashTransaction | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    id: value['id'],
    cash_account_id: value['cash_account_id'],
    amount: value['amount'],
    transaction_date:
      value['transaction_date'] == null
        ? value['transaction_date']
        : value['transaction_date'].toISOString().substring(0, 10),
    description: value['description'],
    type: CashTransactionTypeToJSON(value['type']),
  }
}
