/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmMaterialArrival
 */
export interface ConfirmMaterialArrival {
    /**
     * 
     * @type {string}
     * @memberof ConfirmMaterialArrival
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ConfirmMaterialArrival
     */
    quantity_received?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfirmMaterialArrival
     */
    quantity_lost?: number;
}

/**
 * Check if a given object implements the ConfirmMaterialArrival interface.
 */
export function instanceOfConfirmMaterialArrival(value: object): value is ConfirmMaterialArrival {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ConfirmMaterialArrivalFromJSON(json: any): ConfirmMaterialArrival {
    return ConfirmMaterialArrivalFromJSONTyped(json, false);
}

export function ConfirmMaterialArrivalFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmMaterialArrival {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'quantity_received': json['quantity_received'] == null ? undefined : json['quantity_received'],
        'quantity_lost': json['quantity_lost'] == null ? undefined : json['quantity_lost'],
    };
}

export function ConfirmMaterialArrivalToJSON(json: any): ConfirmMaterialArrival {
    return ConfirmMaterialArrivalToJSONTyped(json, false);
}

export function ConfirmMaterialArrivalToJSONTyped(value?: ConfirmMaterialArrival | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'quantity_received': value['quantity_received'],
        'quantity_lost': value['quantity_lost'],
    };
}

