/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrupdatePurchaseOrderLine
 */
export interface CrupdatePurchaseOrderLine {
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrderLine
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrderLine
     */
    purchase_order_id: string;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrderLine
     */
    material_id: string;
    /**
     * 
     * @type {number}
     * @memberof CrupdatePurchaseOrderLine
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof CrupdatePurchaseOrderLine
     */
    unit_price: number;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrderLine
     */
    comment?: string;
}

/**
 * Check if a given object implements the CrupdatePurchaseOrderLine interface.
 */
export function instanceOfCrupdatePurchaseOrderLine(value: object): value is CrupdatePurchaseOrderLine {
    if (!('purchase_order_id' in value) || value['purchase_order_id'] === undefined) return false;
    if (!('material_id' in value) || value['material_id'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('unit_price' in value) || value['unit_price'] === undefined) return false;
    return true;
}

export function CrupdatePurchaseOrderLineFromJSON(json: any): CrupdatePurchaseOrderLine {
    return CrupdatePurchaseOrderLineFromJSONTyped(json, false);
}

export function CrupdatePurchaseOrderLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrupdatePurchaseOrderLine {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'purchase_order_id': json['purchase_order_id'],
        'material_id': json['material_id'],
        'quantity': json['quantity'],
        'unit_price': json['unit_price'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function CrupdatePurchaseOrderLineToJSON(json: any): CrupdatePurchaseOrderLine {
    return CrupdatePurchaseOrderLineToJSONTyped(json, false);
}

export function CrupdatePurchaseOrderLineToJSONTyped(value?: CrupdatePurchaseOrderLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'purchase_order_id': value['purchase_order_id'],
        'material_id': value['material_id'],
        'quantity': value['quantity'],
        'unit_price': value['unit_price'],
        'comment': value['comment'],
    };
}

