/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrupdateExpenseMoney } from './CrupdateExpenseMoney';
import {
    CrupdateExpenseMoneyFromJSON,
    CrupdateExpenseMoneyFromJSONTyped,
    CrupdateExpenseMoneyToJSON,
    CrupdateExpenseMoneyToJSONTyped,
} from './CrupdateExpenseMoney';
import type { CrupdateWarehouse } from './CrupdateWarehouse';
import {
    CrupdateWarehouseFromJSON,
    CrupdateWarehouseFromJSONTyped,
    CrupdateWarehouseToJSON,
    CrupdateWarehouseToJSONTyped,
} from './CrupdateWarehouse';

/**
 * 
 * @export
 * @interface CrupdateTravelExpense
 */
export interface CrupdateTravelExpense {
    /**
     * 
     * @type {string}
     * @memberof CrupdateTravelExpense
     */
    id?: string;
    /**
     * 
     * @type {CrupdateExpenseMoney}
     * @memberof CrupdateTravelExpense
     */
    expense?: CrupdateExpenseMoney;
    /**
     * 
     * @type {CrupdateWarehouse}
     * @memberof CrupdateTravelExpense
     */
    departure_location?: CrupdateWarehouse;
    /**
     * 
     * @type {CrupdateWarehouse}
     * @memberof CrupdateTravelExpense
     */
    arrival_location?: CrupdateWarehouse;
    /**
     * 
     * @type {Date}
     * @memberof CrupdateTravelExpense
     */
    departure_date?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CrupdateTravelExpense
     */
    arrival_date?: Date;
}

/**
 * Check if a given object implements the CrupdateTravelExpense interface.
 */
export function instanceOfCrupdateTravelExpense(value: object): value is CrupdateTravelExpense {
    return true;
}

export function CrupdateTravelExpenseFromJSON(json: any): CrupdateTravelExpense {
    return CrupdateTravelExpenseFromJSONTyped(json, false);
}

export function CrupdateTravelExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrupdateTravelExpense {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'expense': json['expense'] == null ? undefined : CrupdateExpenseMoneyFromJSON(json['expense']),
        'departure_location': json['departure_location'] == null ? undefined : CrupdateWarehouseFromJSON(json['departure_location']),
        'arrival_location': json['arrival_location'] == null ? undefined : CrupdateWarehouseFromJSON(json['arrival_location']),
        'departure_date': json['departure_date'] == null ? undefined : (new Date(json['departure_date'])),
        'arrival_date': json['arrival_date'] == null ? undefined : (new Date(json['arrival_date'])),
    };
}

export function CrupdateTravelExpenseToJSON(json: any): CrupdateTravelExpense {
    return CrupdateTravelExpenseToJSONTyped(json, false);
}

export function CrupdateTravelExpenseToJSONTyped(value?: CrupdateTravelExpense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'expense': CrupdateExpenseMoneyToJSON(value['expense']),
        'departure_location': CrupdateWarehouseToJSON(value['departure_location']),
        'arrival_location': CrupdateWarehouseToJSON(value['arrival_location']),
        'departure_date': value['departure_date'] == null ? value['departure_date'] : value['departure_date'].toISOString(),
        'arrival_date': value['arrival_date'] == null ? value['arrival_date'] : value['arrival_date'].toISOString(),
    };
}

