/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CrupdateBankFee
 */
export interface CrupdateBankFee {
  /**
   *
   * @type {string}
   * @memberof CrupdateBankFee
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateBankFee
   */
  expense_id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateBankFee
   */
  bank_name?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateBankFee
   */
  description?: string
}

/**
 * Check if a given object implements the CrupdateBankFee interface.
 */
export function instanceOfCrupdateBankFee(value: object): value is CrupdateBankFee {
  return true
}

export function CrupdateBankFeeFromJSON(json: any): CrupdateBankFee {
  return CrupdateBankFeeFromJSONTyped(json, false)
}

export function CrupdateBankFeeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateBankFee {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    expense_id: json['expense_id'] == null ? undefined : json['expense_id'],
    bank_name: json['bank_name'] == null ? undefined : json['bank_name'],
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function CrupdateBankFeeToJSON(json: any): CrupdateBankFee {
  return CrupdateBankFeeToJSONTyped(json, false)
}

export function CrupdateBankFeeToJSONTyped(
  value?: CrupdateBankFee | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    expense_id: value['expense_id'],
    bank_name: value['bank_name'],
    description: value['description'],
  }
}
