/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CrupdateMonetaryMovement
 */
export interface CrupdateMonetaryMovement {
  /**
   *
   * @type {string}
   * @memberof CrupdateMonetaryMovement
   */
  comment?: string
  /**
   *
   * @type {number}
   * @memberof CrupdateMonetaryMovement
   */
  amount?: number
  /**
   *
   * @type {string}
   * @memberof CrupdateMonetaryMovement
   */
  description?: string
}

/**
 * Check if a given object implements the CrupdateMonetaryMovement interface.
 */
export function instanceOfCrupdateMonetaryMovement(
  value: object,
): value is CrupdateMonetaryMovement {
  return true
}

export function CrupdateMonetaryMovementFromJSON(json: any): CrupdateMonetaryMovement {
  return CrupdateMonetaryMovementFromJSONTyped(json, false)
}

export function CrupdateMonetaryMovementFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateMonetaryMovement {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    amount: json['amount'] == null ? undefined : json['amount'],
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function CrupdateMonetaryMovementToJSON(json: any): CrupdateMonetaryMovement {
  return CrupdateMonetaryMovementToJSONTyped(json, false)
}

export function CrupdateMonetaryMovementToJSONTyped(
  value?: CrupdateMonetaryMovement | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    amount: value['amount'],
    description: value['description'],
  }
}
