/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CrupdateExpenseMoney } from './CrupdateExpenseMoney'
import {
  CrupdateExpenseMoneyFromJSON,
  CrupdateExpenseMoneyFromJSONTyped,
  CrupdateExpenseMoneyToJSON,
  CrupdateExpenseMoneyToJSONTyped,
} from './CrupdateExpenseMoney'
import type { PaymentType } from './PaymentType'
import {
  PaymentTypeFromJSON,
  PaymentTypeFromJSONTyped,
  PaymentTypeToJSON,
  PaymentTypeToJSONTyped,
} from './PaymentType'

/**
 *
 * @export
 * @interface CrupdateEmployeePayment
 */
export interface CrupdateEmployeePayment {
  /**
   *
   * @type {string}
   * @memberof CrupdateEmployeePayment
   */
  id?: string
  /**
   *
   * @type {CrupdateExpenseMoney}
   * @memberof CrupdateEmployeePayment
   */
  expense?: CrupdateExpenseMoney
  /**
   *
   * @type {Array<string>}
   * @memberof CrupdateEmployeePayment
   */
  user_ids?: Array<string>
  /**
   *
   * @type {boolean}
   * @memberof CrupdateEmployeePayment
   */
  is_for_team?: boolean
  /**
   *
   * @type {string}
   * @memberof CrupdateEmployeePayment
   */
  team_id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateEmployeePayment
   */
  payment_description?: string
  /**
   *
   * @type {PaymentType}
   * @memberof CrupdateEmployeePayment
   */
  payment_type?: PaymentType
}

/**
 * Check if a given object implements the CrupdateEmployeePayment interface.
 */
export function instanceOfCrupdateEmployeePayment(value: object): value is CrupdateEmployeePayment {
  return true
}

export function CrupdateEmployeePaymentFromJSON(json: any): CrupdateEmployeePayment {
  return CrupdateEmployeePaymentFromJSONTyped(json, false)
}

export function CrupdateEmployeePaymentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateEmployeePayment {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    expense: json['expense'] == null ? undefined : CrupdateExpenseMoneyFromJSON(json['expense']),
    user_ids: json['user_ids'] == null ? undefined : json['user_ids'],
    is_for_team: json['is_for_team'] == null ? undefined : json['is_for_team'],
    team_id: json['team_id'] == null ? undefined : json['team_id'],
    payment_description:
      json['payment_description'] == null ? undefined : json['payment_description'],
    payment_type:
      json['payment_type'] == null ? undefined : PaymentTypeFromJSON(json['payment_type']),
  }
}

export function CrupdateEmployeePaymentToJSON(json: any): CrupdateEmployeePayment {
  return CrupdateEmployeePaymentToJSONTyped(json, false)
}

export function CrupdateEmployeePaymentToJSONTyped(
  value?: CrupdateEmployeePayment | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    expense: CrupdateExpenseMoneyToJSON(value['expense']),
    user_ids: value['user_ids'],
    is_for_team: value['is_for_team'],
    team_id: value['team_id'],
    payment_description: value['payment_description'],
    payment_type: PaymentTypeToJSON(value['payment_type']),
  }
}
