/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrupdateExpenseMoney } from './CrupdateExpenseMoney';
import {
    CrupdateExpenseMoneyFromJSON,
    CrupdateExpenseMoneyFromJSONTyped,
    CrupdateExpenseMoneyToJSON,
    CrupdateExpenseMoneyToJSONTyped,
} from './CrupdateExpenseMoney';
import type { CrupdateWarehouse } from './CrupdateWarehouse';
import {
    CrupdateWarehouseFromJSON,
    CrupdateWarehouseFromJSONTyped,
    CrupdateWarehouseToJSON,
    CrupdateWarehouseToJSONTyped,
} from './CrupdateWarehouse';

/**
 * 
 * @export
 * @interface CrupdatePurchase
 */
export interface CrupdatePurchase {
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchase
     */
    id?: string;
    /**
     * 
     * @type {CrupdateExpenseMoney}
     * @memberof CrupdatePurchase
     */
    expense?: CrupdateExpenseMoney;
    /**
     * 
     * @type {CrupdateWarehouse}
     * @memberof CrupdatePurchase
     */
    supplier?: CrupdateWarehouse;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchase
     */
    equipment?: string;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchase
     */
    material?: string;
    /**
     * 
     * @type {number}
     * @memberof CrupdatePurchase
     */
    quantity?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CrupdatePurchase
     */
    is_equipment?: boolean;
}

/**
 * Check if a given object implements the CrupdatePurchase interface.
 */
export function instanceOfCrupdatePurchase(value: object): value is CrupdatePurchase {
    return true;
}

export function CrupdatePurchaseFromJSON(json: any): CrupdatePurchase {
    return CrupdatePurchaseFromJSONTyped(json, false);
}

export function CrupdatePurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrupdatePurchase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'expense': json['expense'] == null ? undefined : CrupdateExpenseMoneyFromJSON(json['expense']),
        'supplier': json['supplier'] == null ? undefined : CrupdateWarehouseFromJSON(json['supplier']),
        'equipment': json['equipment'] == null ? undefined : json['equipment'],
        'material': json['material'] == null ? undefined : json['material'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'is_equipment': json['is_equipment'] == null ? undefined : json['is_equipment'],
    };
}

export function CrupdatePurchaseToJSON(json: any): CrupdatePurchase {
    return CrupdatePurchaseToJSONTyped(json, false);
}

export function CrupdatePurchaseToJSONTyped(value?: CrupdatePurchase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'expense': CrupdateExpenseMoneyToJSON(value['expense']),
        'supplier': CrupdateWarehouseToJSON(value['supplier']),
        'equipment': value['equipment'],
        'material': value['material'],
        'quantity': value['quantity'],
        'is_equipment': value['is_equipment'],
    };
}

