/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrupdatePurchaseOrderLine } from './CrupdatePurchaseOrderLine';
import {
    CrupdatePurchaseOrderLineFromJSON,
    CrupdatePurchaseOrderLineFromJSONTyped,
    CrupdatePurchaseOrderLineToJSON,
    CrupdatePurchaseOrderLineToJSONTyped,
} from './CrupdatePurchaseOrderLine';
import type { PurchaseOrderStatus } from './PurchaseOrderStatus';
import {
    PurchaseOrderStatusFromJSON,
    PurchaseOrderStatusFromJSONTyped,
    PurchaseOrderStatusToJSON,
    PurchaseOrderStatusToJSONTyped,
} from './PurchaseOrderStatus';

/**
 * 
 * @export
 * @interface CrupdatePurchaseOrder
 */
export interface CrupdatePurchaseOrder {
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrder
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrder
     */
    supplier_id: string;
    /**
     * 
     * @type {Date}
     * @memberof CrupdatePurchaseOrder
     */
    order_date: Date;
    /**
     * 
     * @type {PurchaseOrderStatus}
     * @memberof CrupdatePurchaseOrder
     */
    status: PurchaseOrderStatus;
    /**
     * 
     * @type {number}
     * @memberof CrupdatePurchaseOrder
     */
    total_amount: number;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrder
     */
    company_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrder
     */
    job_id: string;
    /**
     * 
     * @type {Array<CrupdatePurchaseOrderLine>}
     * @memberof CrupdatePurchaseOrder
     */
    lines?: Array<CrupdatePurchaseOrderLine>;
    /**
     * 
     * @type {string}
     * @memberof CrupdatePurchaseOrder
     */
    comment?: string;
}



/**
 * Check if a given object implements the CrupdatePurchaseOrder interface.
 */
export function instanceOfCrupdatePurchaseOrder(value: object): value is CrupdatePurchaseOrder {
    if (!('supplier_id' in value) || value['supplier_id'] === undefined) return false;
    if (!('order_date' in value) || value['order_date'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('total_amount' in value) || value['total_amount'] === undefined) return false;
    if (!('job_id' in value) || value['job_id'] === undefined) return false;
    return true;
}

export function CrupdatePurchaseOrderFromJSON(json: any): CrupdatePurchaseOrder {
    return CrupdatePurchaseOrderFromJSONTyped(json, false);
}

export function CrupdatePurchaseOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrupdatePurchaseOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'supplier_id': json['supplier_id'],
        'order_date': (new Date(json['order_date'])),
        'status': PurchaseOrderStatusFromJSON(json['status']),
        'total_amount': json['total_amount'],
        'company_id': json['company_id'] == null ? undefined : json['company_id'],
        'job_id': json['job_id'],
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(CrupdatePurchaseOrderLineFromJSON)),
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function CrupdatePurchaseOrderToJSON(json: any): CrupdatePurchaseOrder {
    return CrupdatePurchaseOrderToJSONTyped(json, false);
}

export function CrupdatePurchaseOrderToJSONTyped(value?: CrupdatePurchaseOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'supplier_id': value['supplier_id'],
        'order_date': value['order_date'].toISOString().substring(0,10),
        'status': PurchaseOrderStatusToJSON(value['status']),
        'total_amount': value['total_amount'],
        'company_id': value['company_id'],
        'job_id': value['job_id'],
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(CrupdatePurchaseOrderLineToJSON)),
        'comment': value['comment'],
    };
}

