/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Role } from './Role'
import { RoleFromJSON, RoleFromJSONTyped, RoleToJSON, RoleToJSONTyped } from './Role'
import type { Sex } from './Sex'
import { SexFromJSON, SexFromJSONTyped, SexToJSON, SexToJSONTyped } from './Sex'

/**
 *
 * @export
 * @interface CrupdateUser
 */
export interface CrupdateUser {
  /**
   *
   * @type {string}
   * @memberof CrupdateUser
   */
  comment?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateUser
   */
  id?: string
  /**
   *
   * @type {Role}
   * @memberof CrupdateUser
   */
  role?: Role
  /**
   *
   * @type {string}
   * @memberof CrupdateUser
   */
  first_name?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateUser
   */
  last_name?: string
  /**
   *
   * @type {Sex}
   * @memberof CrupdateUser
   */
  sex?: Sex
  /**
   *
   * @type {string}
   * @memberof CrupdateUser
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateUser
   */
  password?: string
}

/**
 * Check if a given object implements the CrupdateUser interface.
 */
export function instanceOfCrupdateUser(value: object): value is CrupdateUser {
  return true
}

export function CrupdateUserFromJSON(json: any): CrupdateUser {
  return CrupdateUserFromJSONTyped(json, false)
}

export function CrupdateUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrupdateUser {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    id: json['id'] == null ? undefined : json['id'],
    role: json['role'] == null ? undefined : RoleFromJSON(json['role']),
    first_name: json['first_name'] == null ? undefined : json['first_name'],
    last_name: json['last_name'] == null ? undefined : json['last_name'],
    sex: json['sex'] == null ? undefined : SexFromJSON(json['sex']),
    email: json['email'] == null ? undefined : json['email'],
    password: json['password'] == null ? undefined : json['password'],
  }
}

export function CrupdateUserToJSON(json: any): CrupdateUser {
  return CrupdateUserToJSONTyped(json, false)
}

export function CrupdateUserToJSONTyped(
  value?: CrupdateUser | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    id: value['id'],
    role: RoleToJSON(value['role']),
    first_name: value['first_name'],
    last_name: value['last_name'],
    sex: SexToJSON(value['sex']),
    email: value['email'],
    password: value['password'],
  }
}
