/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrupdateOtherExpense
 */
export interface CrupdateOtherExpense {
    /**
     * 
     * @type {string}
     * @memberof CrupdateOtherExpense
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CrupdateOtherExpense
     */
    expense_id: string;
    /**
     * ID of the other expense type associated with this expense
     * @type {string}
     * @memberof CrupdateOtherExpense
     */
    other_expense_type_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CrupdateOtherExpense
     */
    description?: string;
}

/**
 * Check if a given object implements the CrupdateOtherExpense interface.
 */
export function instanceOfCrupdateOtherExpense(value: object): value is CrupdateOtherExpense {
    if (!('expense_id' in value) || value['expense_id'] === undefined) return false;
    return true;
}

export function CrupdateOtherExpenseFromJSON(json: any): CrupdateOtherExpense {
    return CrupdateOtherExpenseFromJSONTyped(json, false);
}

export function CrupdateOtherExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrupdateOtherExpense {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'expense_id': json['expense_id'],
        'other_expense_type_id': json['other_expense_type_id'] == null ? undefined : json['other_expense_type_id'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CrupdateOtherExpenseToJSON(json: any): CrupdateOtherExpense {
    return CrupdateOtherExpenseToJSONTyped(json, false);
}

export function CrupdateOtherExpenseToJSONTyped(value?: CrupdateOtherExpense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'expense_id': value['expense_id'],
        'other_expense_type_id': value['other_expense_type_id'],
        'description': value['description'],
    };
}

