/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CrupdateMaterialWarehouse
 */
export interface CrupdateMaterialWarehouse {
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialWarehouse
   */
  material_id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialWarehouse
   */
  warehouse_id?: string
  /**
   *
   * @type {number}
   * @memberof CrupdateMaterialWarehouse
   */
  quantity?: number
}

/**
 * Check if a given object implements the CrupdateMaterialWarehouse interface.
 */
export function instanceOfCrupdateMaterialWarehouse(
  value: object,
): value is CrupdateMaterialWarehouse {
  return true
}

export function CrupdateMaterialWarehouseFromJSON(json: any): CrupdateMaterialWarehouse {
  return CrupdateMaterialWarehouseFromJSONTyped(json, false)
}

export function CrupdateMaterialWarehouseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateMaterialWarehouse {
  if (json == null) {
    return json
  }
  return {
    material_id: json['material_id'] == null ? undefined : json['material_id'],
    warehouse_id: json['warehouse_id'] == null ? undefined : json['warehouse_id'],
    quantity: json['quantity'] == null ? undefined : json['quantity'],
  }
}

export function CrupdateMaterialWarehouseToJSON(json: any): CrupdateMaterialWarehouse {
  return CrupdateMaterialWarehouseToJSONTyped(json, false)
}

export function CrupdateMaterialWarehouseToJSONTyped(
  value?: CrupdateMaterialWarehouse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    material_id: value['material_id'],
    warehouse_id: value['warehouse_id'],
    quantity: value['quantity'],
  }
}
