/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { TaskPriority } from './TaskPriority'
import {
  TaskPriorityFromJSON,
  TaskPriorityFromJSONTyped,
  TaskPriorityToJSON,
  TaskPriorityToJSONTyped,
} from './TaskPriority'

/**
 *
 * @export
 * @interface CrupdateTaskSchedule
 */
export interface CrupdateTaskSchedule {
  /**
   *
   * @type {string}
   * @memberof CrupdateTaskSchedule
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateTaskSchedule
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateTaskSchedule
   */
  description?: string
  /**
   *
   * @type {TaskPriority}
   * @memberof CrupdateTaskSchedule
   */
  priority?: TaskPriority
  /**
   * Cron expression for recurring schedule
   * @type {string}
   * @memberof CrupdateTaskSchedule
   */
  frequency?: string
  /**
   *
   * @type {Date}
   * @memberof CrupdateTaskSchedule
   */
  scheduled_date?: Date
  /**
   *
   * @type {string}
   * @memberof CrupdateTaskSchedule
   */
  company_id?: string
  /**
   *
   * @type {Array<string>}
   * @memberof CrupdateTaskSchedule
   */
  assigned_user_ids?: Array<string>
  /**
   *
   * @type {string}
   * @memberof CrupdateTaskSchedule
   */
  comment?: string
}

/**
 * Check if a given object implements the CrupdateTaskSchedule interface.
 */
export function instanceOfCrupdateTaskSchedule(value: object): value is CrupdateTaskSchedule {
  return true
}

export function CrupdateTaskScheduleFromJSON(json: any): CrupdateTaskSchedule {
  return CrupdateTaskScheduleFromJSONTyped(json, false)
}

export function CrupdateTaskScheduleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateTaskSchedule {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    title: json['title'] == null ? undefined : json['title'],
    description: json['description'] == null ? undefined : json['description'],
    priority: json['priority'] == null ? undefined : TaskPriorityFromJSON(json['priority']),
    frequency: json['frequency'] == null ? undefined : json['frequency'],
    scheduled_date: json['scheduled_date'] == null ? undefined : new Date(json['scheduled_date']),
    company_id: json['company_id'] == null ? undefined : json['company_id'],
    assigned_user_ids: json['assigned_user_ids'] == null ? undefined : json['assigned_user_ids'],
    comment: json['comment'] == null ? undefined : json['comment'],
  }
}

export function CrupdateTaskScheduleToJSON(json: any): CrupdateTaskSchedule {
  return CrupdateTaskScheduleToJSONTyped(json, false)
}

export function CrupdateTaskScheduleToJSONTyped(
  value?: CrupdateTaskSchedule | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    title: value['title'],
    description: value['description'],
    priority: TaskPriorityToJSON(value['priority']),
    frequency: value['frequency'],
    scheduled_date:
      value['scheduled_date'] == null
        ? value['scheduled_date']
        : value['scheduled_date'].toISOString().substring(0, 10),
    company_id: value['company_id'],
    assigned_user_ids: value['assigned_user_ids'],
    comment: value['comment'],
  }
}
