/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CrupdateDepartment
 */
export interface CrupdateDepartment {
  /**
   *
   * @type {string}
   * @memberof CrupdateDepartment
   */
  comment?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateDepartment
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateDepartment
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateDepartment
   */
  description?: string
}

/**
 * Check if a given object implements the CrupdateDepartment interface.
 */
export function instanceOfCrupdateDepartment(value: object): value is CrupdateDepartment {
  return true
}

export function CrupdateDepartmentFromJSON(json: any): CrupdateDepartment {
  return CrupdateDepartmentFromJSONTyped(json, false)
}

export function CrupdateDepartmentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateDepartment {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function CrupdateDepartmentToJSON(json: any): CrupdateDepartment {
  return CrupdateDepartmentToJSONTyped(json, false)
}

export function CrupdateDepartmentToJSONTyped(
  value?: CrupdateDepartment | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    id: value['id'],
    name: value['name'],
    description: value['description'],
  }
}
