/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CrupdateBudgetLine
 */
export interface CrupdateBudgetLine {
  /**
   *
   * @type {string}
   * @memberof CrupdateBudgetLine
   */
  comment?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateBudgetLine
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateBudgetLine
   */
  company_id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateBudgetLine
   */
  category?: string
  /**
   *
   * @type {number}
   * @memberof CrupdateBudgetLine
   */
  planned_amount?: number
  /**
   *
   * @type {number}
   * @memberof CrupdateBudgetLine
   */
  actual_amount?: number
  /**
   *
   * @type {Date}
   * @memberof CrupdateBudgetLine
   */
  period_start?: Date
  /**
   *
   * @type {Date}
   * @memberof CrupdateBudgetLine
   */
  period_end?: Date
  /**
   *
   * @type {string}
   * @memberof CrupdateBudgetLine
   */
  description?: string
}

/**
 * Check if a given object implements the CrupdateBudgetLine interface.
 */
export function instanceOfCrupdateBudgetLine(value: object): value is CrupdateBudgetLine {
  return true
}

export function CrupdateBudgetLineFromJSON(json: any): CrupdateBudgetLine {
  return CrupdateBudgetLineFromJSONTyped(json, false)
}

export function CrupdateBudgetLineFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateBudgetLine {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    id: json['id'] == null ? undefined : json['id'],
    company_id: json['company_id'] == null ? undefined : json['company_id'],
    category: json['category'] == null ? undefined : json['category'],
    planned_amount: json['planned_amount'] == null ? undefined : json['planned_amount'],
    actual_amount: json['actual_amount'] == null ? undefined : json['actual_amount'],
    period_start: json['period_start'] == null ? undefined : new Date(json['period_start']),
    period_end: json['period_end'] == null ? undefined : new Date(json['period_end']),
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function CrupdateBudgetLineToJSON(json: any): CrupdateBudgetLine {
  return CrupdateBudgetLineToJSONTyped(json, false)
}

export function CrupdateBudgetLineToJSONTyped(
  value?: CrupdateBudgetLine | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    id: value['id'],
    company_id: value['company_id'],
    category: value['category'],
    planned_amount: value['planned_amount'],
    actual_amount: value['actual_amount'],
    period_start:
      value['period_start'] == null
        ? value['period_start']
        : value['period_start'].toISOString().substring(0, 10),
    period_end:
      value['period_end'] == null
        ? value['period_end']
        : value['period_end'].toISOString().substring(0, 10),
    description: value['description'],
  }
}
