/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CrupdateMaterialConsumption
 */
export interface CrupdateMaterialConsumption {
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialConsumption
   */
  comment?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialConsumption
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialConsumption
   */
  material_id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialConsumption
   */
  warehouse_id?: string
  /**
   *
   * @type {number}
   * @memberof CrupdateMaterialConsumption
   */
  quantity?: number
  /**
   *
   * @type {Date}
   * @memberof CrupdateMaterialConsumption
   */
  consumption_date?: Date
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialConsumption
   */
  job_id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialConsumption
   */
  reason?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateMaterialConsumption
   */
  consumption_status?: string
}

/**
 * Check if a given object implements the CrupdateMaterialConsumption interface.
 */
export function instanceOfCrupdateMaterialConsumption(
  value: object,
): value is CrupdateMaterialConsumption {
  return true
}

export function CrupdateMaterialConsumptionFromJSON(json: any): CrupdateMaterialConsumption {
  return CrupdateMaterialConsumptionFromJSONTyped(json, false)
}

export function CrupdateMaterialConsumptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateMaterialConsumption {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    id: json['id'] == null ? undefined : json['id'],
    material_id: json['material_id'] == null ? undefined : json['material_id'],
    warehouse_id: json['warehouse_id'] == null ? undefined : json['warehouse_id'],
    quantity: json['quantity'] == null ? undefined : json['quantity'],
    consumption_date:
      json['consumption_date'] == null ? undefined : new Date(json['consumption_date']),
    job_id: json['job_id'] == null ? undefined : json['job_id'],
    reason: json['reason'] == null ? undefined : json['reason'],
    consumption_status: json['consumption_status'] == null ? undefined : json['consumption_status'],
  }
}

export function CrupdateMaterialConsumptionToJSON(json: any): CrupdateMaterialConsumption {
  return CrupdateMaterialConsumptionToJSONTyped(json, false)
}

export function CrupdateMaterialConsumptionToJSONTyped(
  value?: CrupdateMaterialConsumption | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    id: value['id'],
    material_id: value['material_id'],
    warehouse_id: value['warehouse_id'],
    quantity: value['quantity'],
    consumption_date:
      value['consumption_date'] == null
        ? value['consumption_date']
        : value['consumption_date'].toISOString().substring(0, 10),
    job_id: value['job_id'],
    reason: value['reason'],
    consumption_status: value['consumption_status'],
  }
}
