/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CrupdateIncomeReceipt
 */
export interface CrupdateIncomeReceipt {
  /**
   *
   * @type {string}
   * @memberof CrupdateIncomeReceipt
   */
  id?: string
  /**
   *
   * @type {Date}
   * @memberof CrupdateIncomeReceipt
   */
  payment_date?: Date
  /**
   *
   * @type {number}
   * @memberof CrupdateIncomeReceipt
   */
  amount?: number
  /**
   * ID of the income this receipt is related to
   * @type {string}
   * @memberof CrupdateIncomeReceipt
   */
  income_id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateIncomeReceipt
   */
  comment?: string
}

/**
 * Check if a given object implements the CrupdateIncomeReceipt interface.
 */
export function instanceOfCrupdateIncomeReceipt(value: object): value is CrupdateIncomeReceipt {
  return true
}

export function CrupdateIncomeReceiptFromJSON(json: any): CrupdateIncomeReceipt {
  return CrupdateIncomeReceiptFromJSONTyped(json, false)
}

export function CrupdateIncomeReceiptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateIncomeReceipt {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    payment_date: json['payment_date'] == null ? undefined : new Date(json['payment_date']),
    amount: json['amount'] == null ? undefined : json['amount'],
    income_id: json['income_id'] == null ? undefined : json['income_id'],
    comment: json['comment'] == null ? undefined : json['comment'],
  }
}

export function CrupdateIncomeReceiptToJSON(json: any): CrupdateIncomeReceipt {
  return CrupdateIncomeReceiptToJSONTyped(json, false)
}

export function CrupdateIncomeReceiptToJSONTyped(
  value?: CrupdateIncomeReceipt | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    payment_date:
      value['payment_date'] == null
        ? value['payment_date']
        : value['payment_date'].toISOString().substring(0, 10),
    amount: value['amount'],
    income_id: value['income_id'],
    comment: value['comment'],
  }
}
