/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CrupdateOtherExpenseType
 */
export interface CrupdateOtherExpenseType {
  /**
   *
   * @type {string}
   * @memberof CrupdateOtherExpenseType
   */
  comment?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateOtherExpenseType
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateOtherExpenseType
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof CrupdateOtherExpenseType
   */
  description?: string
  /**
   * ID of the company this other expense type belongs to
   * @type {string}
   * @memberof CrupdateOtherExpenseType
   */
  company_id?: string
}

/**
 * Check if a given object implements the CrupdateOtherExpenseType interface.
 */
export function instanceOfCrupdateOtherExpenseType(
  value: object,
): value is CrupdateOtherExpenseType {
  return true
}

export function CrupdateOtherExpenseTypeFromJSON(json: any): CrupdateOtherExpenseType {
  return CrupdateOtherExpenseTypeFromJSONTyped(json, false)
}

export function CrupdateOtherExpenseTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrupdateOtherExpenseType {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    company_id: json['company_id'] == null ? undefined : json['company_id'],
  }
}

export function CrupdateOtherExpenseTypeToJSON(json: any): CrupdateOtherExpenseType {
  return CrupdateOtherExpenseTypeToJSONTyped(json, false)
}

export function CrupdateOtherExpenseTypeToJSONTyped(
  value?: CrupdateOtherExpenseType | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    id: value['id'],
    name: value['name'],
    description: value['description'],
    company_id: value['company_id'],
  }
}
