/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Department
 */
export interface Department {
  /**
   *
   * @type {string}
   * @memberof Department
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Department
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof Department
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof Department
   */
  company_id?: string
  /**
   *
   * @type {Date}
   * @memberof Department
   */
  birth_date?: Date
  /**
   *
   * @type {string}
   * @memberof Department
   */
  manager_id?: string
  /**
   *
   * @type {string}
   * @memberof Department
   */
  department_id?: string
}

/**
 * Check if a given object implements the Department interface.
 */
export function instanceOfDepartment(value: object): value is Department {
  return true
}

export function DepartmentFromJSON(json: any): Department {
  return DepartmentFromJSONTyped(json, false)
}

export function DepartmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Department {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    company_id: json['company_id'] == null ? undefined : json['company_id'],
    birth_date: json['birth_date'] == null ? undefined : new Date(json['birth_date']),
    manager_id: json['manager_id'] == null ? undefined : json['manager_id'],
    department_id: json['department_id'] == null ? undefined : json['department_id'],
  }
}

export function DepartmentToJSON(json: any): Department {
  return DepartmentToJSONTyped(json, false)
}

export function DepartmentToJSONTyped(
  value?: Department | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    name: value['name'],
    description: value['description'],
    company_id: value['company_id'],
    birth_date:
      value['birth_date'] == null
        ? value['birth_date']
        : value['birth_date'].toISOString().substring(0, 10),
    manager_id: value['manager_id'],
    department_id: value['department_id'],
  }
}
