/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'

/**
 *
 * @export
 * @interface EmployeeLeaveConfig
 */
export interface EmployeeLeaveConfig {
  /**
   *
   * @type {string}
   * @memberof EmployeeLeaveConfig
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof EmployeeLeaveConfig
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof EmployeeLeaveConfig
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof EmployeeLeaveConfig
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof EmployeeLeaveConfig
   */
  updated_by?: AuditUser
  /**
   *
   * @type {string}
   * @memberof EmployeeLeaveConfig
   */
  id?: string
  /**
   *
   * @type {Date}
   * @memberof EmployeeLeaveConfig
   */
  hire_date?: Date
  /**
   *
   * @type {string}
   * @memberof EmployeeLeaveConfig
   */
  contract_type?: string
  /**
   *
   * @type {number}
   * @memberof EmployeeLeaveConfig
   */
  vacation_days_per_month?: number
  /**
   *
   * @type {Date}
   * @memberof EmployeeLeaveConfig
   */
  end_date?: Date
  /**
   *
   * @type {number}
   * @memberof EmployeeLeaveConfig
   */
  weekly_hours?: number
}

/**
 * Check if a given object implements the EmployeeLeaveConfig interface.
 */
export function instanceOfEmployeeLeaveConfig(value: object): value is EmployeeLeaveConfig {
  return true
}

export function EmployeeLeaveConfigFromJSON(json: any): EmployeeLeaveConfig {
  return EmployeeLeaveConfigFromJSONTyped(json, false)
}

export function EmployeeLeaveConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EmployeeLeaveConfig {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    id: json['id'] == null ? undefined : json['id'],
    hire_date: json['hire_date'] == null ? undefined : new Date(json['hire_date']),
    contract_type: json['contract_type'] == null ? undefined : json['contract_type'],
    vacation_days_per_month:
      json['vacation_days_per_month'] == null ? undefined : json['vacation_days_per_month'],
    end_date: json['end_date'] == null ? undefined : new Date(json['end_date']),
    weekly_hours: json['weekly_hours'] == null ? undefined : json['weekly_hours'],
  }
}

export function EmployeeLeaveConfigToJSON(json: any): EmployeeLeaveConfig {
  return EmployeeLeaveConfigToJSONTyped(json, false)
}

export function EmployeeLeaveConfigToJSONTyped(
  value?: EmployeeLeaveConfig | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    id: value['id'],
    hire_date:
      value['hire_date'] == null
        ? value['hire_date']
        : value['hire_date'].toISOString().substring(0, 10),
    contract_type: value['contract_type'],
    vacation_days_per_month: value['vacation_days_per_month'],
    end_date:
      value['end_date'] == null
        ? value['end_date']
        : value['end_date'].toISOString().substring(0, 10),
    weekly_hours: value['weekly_hours'],
  }
}
