/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'

/**
 *
 * @export
 * @interface EquipmentUsage
 */
export interface EquipmentUsage {
  /**
   *
   * @type {string}
   * @memberof EquipmentUsage
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof EquipmentUsage
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof EquipmentUsage
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof EquipmentUsage
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof EquipmentUsage
   */
  updated_by?: AuditUser
  /**
   *
   * @type {string}
   * @memberof EquipmentUsage
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof EquipmentUsage
   */
  equipment_id?: string
  /**
   *
   * @type {string}
   * @memberof EquipmentUsage
   */
  job_id?: string
  /**
   *
   * @type {Date}
   * @memberof EquipmentUsage
   */
  start_time?: Date
  /**
   *
   * @type {Date}
   * @memberof EquipmentUsage
   */
  end_time?: Date
  /**
   *
   * @type {string}
   * @memberof EquipmentUsage
   */
  source_location?: string
  /**
   *
   * @type {string}
   * @memberof EquipmentUsage
   */
  usage_status?: string
  /**
   *
   * @type {string}
   * @memberof EquipmentUsage
   */
  used_by?: string
}

/**
 * Check if a given object implements the EquipmentUsage interface.
 */
export function instanceOfEquipmentUsage(value: object): value is EquipmentUsage {
  return true
}

export function EquipmentUsageFromJSON(json: any): EquipmentUsage {
  return EquipmentUsageFromJSONTyped(json, false)
}

export function EquipmentUsageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EquipmentUsage {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    id: json['id'] == null ? undefined : json['id'],
    equipment_id: json['equipment_id'] == null ? undefined : json['equipment_id'],
    job_id: json['job_id'] == null ? undefined : json['job_id'],
    start_time: json['start_time'] == null ? undefined : new Date(json['start_time']),
    end_time: json['end_time'] == null ? undefined : new Date(json['end_time']),
    source_location: json['source_location'] == null ? undefined : json['source_location'],
    usage_status: json['usage_status'] == null ? undefined : json['usage_status'],
    used_by: json['used_by'] == null ? undefined : json['used_by'],
  }
}

export function EquipmentUsageToJSON(json: any): EquipmentUsage {
  return EquipmentUsageToJSONTyped(json, false)
}

export function EquipmentUsageToJSONTyped(
  value?: EquipmentUsage | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    id: value['id'],
    equipment_id: value['equipment_id'],
    job_id: value['job_id'],
    start_time:
      value['start_time'] == null ? value['start_time'] : value['start_time'].toISOString(),
    end_time: value['end_time'] == null ? value['end_time'] : value['end_time'].toISOString(),
    source_location: value['source_location'],
    usage_status: value['usage_status'],
    used_by: value['used_by'],
  }
}
