/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'
import type { CrupdateWarehouse } from './CrupdateWarehouse'
import {
  CrupdateWarehouseFromJSON,
  CrupdateWarehouseFromJSONTyped,
  CrupdateWarehouseToJSON,
  CrupdateWarehouseToJSONTyped,
} from './CrupdateWarehouse'
import type { Maintenance } from './Maintenance'
import {
  MaintenanceFromJSON,
  MaintenanceFromJSONTyped,
  MaintenanceToJSON,
  MaintenanceToJSONTyped,
} from './Maintenance'

/**
 *
 * @export
 * @interface Equipment
 */
export interface Equipment {
  /**
   *
   * @type {string}
   * @memberof Equipment
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof Equipment
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof Equipment
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof Equipment
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof Equipment
   */
  updated_by?: AuditUser
  /**
   *
   * @type {string}
   * @memberof Equipment
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Equipment
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof Equipment
   */
  description?: string
  /**
   *
   * @type {CrupdateWarehouse}
   * @memberof Equipment
   */
  warehouse?: CrupdateWarehouse
  /**
   *
   * @type {number}
   * @memberof Equipment
   */
  floor_number?: number
  /**
   *
   * @type {number}
   * @memberof Equipment
   */
  storage_number?: number
  /**
   * Whether the equipment is broken
   * @type {boolean}
   * @memberof Equipment
   */
  est_en_panne?: boolean
  /**
   *
   * @type {number}
   * @memberof Equipment
   */
  purchase_price?: number
  /**
   *
   * @type {Date}
   * @memberof Equipment
   */
  purchase_date?: Date
  /**
   *
   * @type {string}
   * @memberof Equipment
   */
  category?: string
  /**
   * Maintenance records for this equipment
   * @type {Array<Maintenance>}
   * @memberof Equipment
   */
  maintenances?: Array<Maintenance>
}

/**
 * Check if a given object implements the Equipment interface.
 */
export function instanceOfEquipment(value: object): value is Equipment {
  return true
}

export function EquipmentFromJSON(json: any): Equipment {
  return EquipmentFromJSONTyped(json, false)
}

export function EquipmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Equipment {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    warehouse: json['warehouse'] == null ? undefined : CrupdateWarehouseFromJSON(json['warehouse']),
    floor_number: json['floor_number'] == null ? undefined : json['floor_number'],
    storage_number: json['storage_number'] == null ? undefined : json['storage_number'],
    est_en_panne: json['est_en_panne'] == null ? undefined : json['est_en_panne'],
    purchase_price: json['purchase_price'] == null ? undefined : json['purchase_price'],
    purchase_date: json['purchase_date'] == null ? undefined : new Date(json['purchase_date']),
    category: json['category'] == null ? undefined : json['category'],
    maintenances:
      json['maintenances'] == null
        ? undefined
        : (json['maintenances'] as Array<any>).map(MaintenanceFromJSON),
  }
}

export function EquipmentToJSON(json: any): Equipment {
  return EquipmentToJSONTyped(json, false)
}

export function EquipmentToJSONTyped(
  value?: Equipment | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    id: value['id'],
    name: value['name'],
    description: value['description'],
    warehouse: CrupdateWarehouseToJSON(value['warehouse']),
    floor_number: value['floor_number'],
    storage_number: value['storage_number'],
    est_en_panne: value['est_en_panne'],
    purchase_price: value['purchase_price'],
    purchase_date:
      value['purchase_date'] == null
        ? value['purchase_date']
        : value['purchase_date'].toISOString().substring(0, 10),
    category: value['category'],
    maintenances:
      value['maintenances'] == null
        ? undefined
        : (value['maintenances'] as Array<any>).map(MaintenanceToJSON),
  }
}
