/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrupdateJob } from './CrupdateJob';
import {
    CrupdateJobFromJSON,
    CrupdateJobFromJSONTyped,
    CrupdateJobToJSON,
    CrupdateJobToJSONTyped,
} from './CrupdateJob';

/**
 * 
 * @export
 * @interface ExpenseMoney
 */
export interface ExpenseMoney {
    /**
     * 
     * @type {number}
     * @memberof ExpenseMoney
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseMoney
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseMoney
     */
    id?: string;
    /**
     * Job this expense is related to
     * @type {CrupdateJob}
     * @memberof ExpenseMoney
     */
    job?: CrupdateJob;
}

/**
 * Check if a given object implements the ExpenseMoney interface.
 */
export function instanceOfExpenseMoney(value: object): value is ExpenseMoney {
    return true;
}

export function ExpenseMoneyFromJSON(json: any): ExpenseMoney {
    return ExpenseMoneyFromJSONTyped(json, false);
}

export function ExpenseMoneyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseMoney {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'job': json['job'] == null ? undefined : CrupdateJobFromJSON(json['job']),
    };
}

export function ExpenseMoneyToJSON(json: any): ExpenseMoney {
    return ExpenseMoneyToJSONTyped(json, false);
}

export function ExpenseMoneyToJSONTyped(value?: ExpenseMoney | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'description': value['description'],
        'id': value['id'],
        'job': CrupdateJobToJSON(value['job']),
    };
}

