/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { EntityType } from './EntityType'
import {
  EntityTypeFromJSON,
  EntityTypeFromJSONTyped,
  EntityTypeToJSON,
  EntityTypeToJSONTyped,
} from './EntityType'

/**
 *
 * @export
 * @interface History
 */
export interface History {
  /**
   *
   * @type {string}
   * @memberof History
   */
  id?: string
  /**
   * Serialized previous value of the entity
   * @type {string}
   * @memberof History
   */
  previous_value?: string
  /**
   * Serialized new value of the entity
   * @type {string}
   * @memberof History
   */
  new_value?: string
  /**
   * ID of the user who made the modification
   * @type {string}
   * @memberof History
   */
  user_id?: string
  /**
   * Date and time of the modification
   * @type {Date}
   * @memberof History
   */
  modified_at?: Date
  /**
   *
   * @type {EntityType}
   * @memberof History
   */
  entity_type?: EntityType
  /**
   * ID of the modified entity
   * @type {string}
   * @memberof History
   */
  entity_id?: string
}

/**
 * Check if a given object implements the History interface.
 */
export function instanceOfHistory(value: object): value is History {
  return true
}

export function HistoryFromJSON(json: any): History {
  return HistoryFromJSONTyped(json, false)
}

export function HistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): History {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    previous_value: json['previous_value'] == null ? undefined : json['previous_value'],
    new_value: json['new_value'] == null ? undefined : json['new_value'],
    user_id: json['user_id'] == null ? undefined : json['user_id'],
    modified_at: json['modified_at'] == null ? undefined : new Date(json['modified_at']),
    entity_type: json['entity_type'] == null ? undefined : EntityTypeFromJSON(json['entity_type']),
    entity_id: json['entity_id'] == null ? undefined : json['entity_id'],
  }
}

export function HistoryToJSON(json: any): History {
  return HistoryToJSONTyped(json, false)
}

export function HistoryToJSONTyped(
  value?: History | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    previous_value: value['previous_value'],
    new_value: value['new_value'],
    user_id: value['user_id'],
    modified_at:
      value['modified_at'] == null ? value['modified_at'] : value['modified_at'].toISOString(),
    entity_type: EntityTypeToJSON(value['entity_type']),
    entity_id: value['entity_id'],
  }
}
