/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CrupdateJob } from './CrupdateJob'
import {
  CrupdateJobFromJSON,
  CrupdateJobFromJSONTyped,
  CrupdateJobToJSON,
  CrupdateJobToJSONTyped,
} from './CrupdateJob'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'
import type { IncomeType } from './IncomeType'
import {
  IncomeTypeFromJSON,
  IncomeTypeFromJSONTyped,
  IncomeTypeToJSON,
  IncomeTypeToJSONTyped,
} from './IncomeType'
import type { IncomeReceipt } from './IncomeReceipt'
import {
  IncomeReceiptFromJSON,
  IncomeReceiptFromJSONTyped,
  IncomeReceiptToJSON,
  IncomeReceiptToJSONTyped,
} from './IncomeReceipt'

/**
 *
 * @export
 * @interface IncomeMoney
 */
export interface IncomeMoney {
  /**
   *
   * @type {string}
   * @memberof IncomeMoney
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof IncomeMoney
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof IncomeMoney
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof IncomeMoney
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof IncomeMoney
   */
  updated_by?: AuditUser
  /**
   *
   * @type {number}
   * @memberof IncomeMoney
   */
  amount?: number
  /**
   *
   * @type {string}
   * @memberof IncomeMoney
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof IncomeMoney
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof IncomeMoney
   */
  source_organization?: string
  /**
   *
   * @type {string}
   * @memberof IncomeMoney
   */
  invoice_reference?: string
  /**
   *
   * @type {Date}
   * @memberof IncomeMoney
   */
  billing_start_date?: Date
  /**
   * Date when the client started providing the invoice
   * @type {Date}
   * @memberof IncomeMoney
   */
  facturation_date?: Date
  /**
   * Job this income is related to
   * @type {CrupdateJob}
   * @memberof IncomeMoney
   */
  job?: CrupdateJob
  /**
   * Type of income associated with this income
   * @type {IncomeType}
   * @memberof IncomeMoney
   */
  income_type?: IncomeType
  /**
   * Payments received for this income
   * @type {Array<IncomeReceipt>}
   * @memberof IncomeMoney
   */
  receipts?: Array<IncomeReceipt>
  /**
   * Remaining unpaid amount (amount - sum of receipts)
   * @type {number}
   * @memberof IncomeMoney
   */
  remaining_amount?: number
}

/**
 * Check if a given object implements the IncomeMoney interface.
 */
export function instanceOfIncomeMoney(value: object): value is IncomeMoney {
  return true
}

export function IncomeMoneyFromJSON(json: any): IncomeMoney {
  return IncomeMoneyFromJSONTyped(json, false)
}

export function IncomeMoneyFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeMoney {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    amount: json['amount'] == null ? undefined : json['amount'],
    description: json['description'] == null ? undefined : json['description'],
    id: json['id'] == null ? undefined : json['id'],
    source_organization:
      json['source_organization'] == null ? undefined : json['source_organization'],
    invoice_reference: json['invoice_reference'] == null ? undefined : json['invoice_reference'],
    billing_start_date:
      json['billing_start_date'] == null ? undefined : new Date(json['billing_start_date']),
    facturation_date:
      json['facturation_date'] == null ? undefined : new Date(json['facturation_date']),
    job: json['job'] == null ? undefined : CrupdateJobFromJSON(json['job']),
    income_type: json['income_type'] == null ? undefined : IncomeTypeFromJSON(json['income_type']),
    receipts:
      json['receipts'] == null
        ? undefined
        : (json['receipts'] as Array<any>).map(IncomeReceiptFromJSON),
    remaining_amount: json['remaining_amount'] == null ? undefined : json['remaining_amount'],
  }
}

export function IncomeMoneyToJSON(json: any): IncomeMoney {
  return IncomeMoneyToJSONTyped(json, false)
}

export function IncomeMoneyToJSONTyped(
  value?: IncomeMoney | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    amount: value['amount'],
    description: value['description'],
    id: value['id'],
    source_organization: value['source_organization'],
    invoice_reference: value['invoice_reference'],
    billing_start_date:
      value['billing_start_date'] == null
        ? value['billing_start_date']
        : value['billing_start_date'].toISOString().substring(0, 10),
    facturation_date:
      value['facturation_date'] == null
        ? value['facturation_date']
        : value['facturation_date'].toISOString(),
    job: CrupdateJobToJSON(value['job']),
    income_type: IncomeTypeToJSON(value['income_type']),
    receipts:
      value['receipts'] == null
        ? undefined
        : (value['receipts'] as Array<any>).map(IncomeReceiptToJSON),
    remaining_amount: value['remaining_amount'],
  }
}
