/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IncomeMoney } from './IncomeMoney';
import {
    IncomeMoneyFromJSON,
    IncomeMoneyFromJSONTyped,
    IncomeMoneyToJSON,
    IncomeMoneyToJSONTyped,
} from './IncomeMoney';

/**
 * 
 * @export
 * @interface IncomeReceipt
 */
export interface IncomeReceipt {
    /**
     * 
     * @type {string}
     * @memberof IncomeReceipt
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof IncomeReceipt
     */
    payment_date?: Date;
    /**
     * 
     * @type {number}
     * @memberof IncomeReceipt
     */
    amount?: number;
    /**
     * Income this receipt is related to
     * @type {IncomeMoney}
     * @memberof IncomeReceipt
     */
    income?: IncomeMoney;
}

/**
 * Check if a given object implements the IncomeReceipt interface.
 */
export function instanceOfIncomeReceipt(value: object): value is IncomeReceipt {
    return true;
}

export function IncomeReceiptFromJSON(json: any): IncomeReceipt {
    return IncomeReceiptFromJSONTyped(json, false);
}

export function IncomeReceiptFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeReceipt {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'payment_date': json['payment_date'] == null ? undefined : (new Date(json['payment_date'])),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'income': json['income'] == null ? undefined : IncomeMoneyFromJSON(json['income']),
    };
}

export function IncomeReceiptToJSON(json: any): IncomeReceipt {
    return IncomeReceiptToJSONTyped(json, false);
}

export function IncomeReceiptToJSONTyped(value?: IncomeReceipt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'payment_date': value['payment_date'] == null ? value['payment_date'] : value['payment_date'].toISOString().substring(0,10),
        'amount': value['amount'],
        'income': IncomeMoneyToJSON(value['income']),
    };
}

