/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LeaveStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const
export type LeaveStatus = (typeof LeaveStatus)[keyof typeof LeaveStatus]

export function instanceOfLeaveStatus(value: any): boolean {
  for (const key in LeaveStatus) {
    if (Object.prototype.hasOwnProperty.call(LeaveStatus, key)) {
      if (LeaveStatus[key as keyof typeof LeaveStatus] === value) {
        return true
      }
    }
  }
  return false
}

export function LeaveStatusFromJSON(json: any): LeaveStatus {
  return LeaveStatusFromJSONTyped(json, false)
}

export function LeaveStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaveStatus {
  return json as LeaveStatus
}

export function LeaveStatusToJSON(value?: LeaveStatus | null): any {
  return value as any
}

export function LeaveStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): LeaveStatus {
  return value as LeaveStatus
}
