/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'
import type { CrupdateLoan } from './CrupdateLoan'
import {
  CrupdateLoanFromJSON,
  CrupdateLoanFromJSONTyped,
  CrupdateLoanToJSON,
  CrupdateLoanToJSONTyped,
} from './CrupdateLoan'

/**
 *
 * @export
 * @interface LoanRepayment
 */
export interface LoanRepayment {
  /**
   *
   * @type {string}
   * @memberof LoanRepayment
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof LoanRepayment
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof LoanRepayment
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof LoanRepayment
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof LoanRepayment
   */
  updated_by?: AuditUser
  /**
   *
   * @type {string}
   * @memberof LoanRepayment
   */
  id?: string
  /**
   *
   * @type {Date}
   * @memberof LoanRepayment
   */
  payment_date?: Date
  /**
   * Total repayment amount
   * @type {number}
   * @memberof LoanRepayment
   */
  amount?: number
  /**
   * Portion of the payment that goes to principal (auto-calculated)
   * @type {number}
   * @memberof LoanRepayment
   */
  principal_portion?: number
  /**
   * Portion of the payment that goes to interest (auto-calculated)
   * @type {number}
   * @memberof LoanRepayment
   */
  interest_portion?: number
  /**
   * Loan this repayment is related to
   * @type {CrupdateLoan}
   * @memberof LoanRepayment
   */
  loan?: CrupdateLoan
}

/**
 * Check if a given object implements the LoanRepayment interface.
 */
export function instanceOfLoanRepayment(value: object): value is LoanRepayment {
  return true
}

export function LoanRepaymentFromJSON(json: any): LoanRepayment {
  return LoanRepaymentFromJSONTyped(json, false)
}

export function LoanRepaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoanRepayment {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    id: json['id'] == null ? undefined : json['id'],
    payment_date: json['payment_date'] == null ? undefined : new Date(json['payment_date']),
    amount: json['amount'] == null ? undefined : json['amount'],
    principal_portion: json['principal_portion'] == null ? undefined : json['principal_portion'],
    interest_portion: json['interest_portion'] == null ? undefined : json['interest_portion'],
    loan: json['loan'] == null ? undefined : CrupdateLoanFromJSON(json['loan']),
  }
}

export function LoanRepaymentToJSON(json: any): LoanRepayment {
  return LoanRepaymentToJSONTyped(json, false)
}

export function LoanRepaymentToJSONTyped(
  value?: LoanRepayment | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    id: value['id'],
    payment_date:
      value['payment_date'] == null
        ? value['payment_date']
        : value['payment_date'].toISOString().substring(0, 10),
    amount: value['amount'],
    principal_portion: value['principal_portion'],
    interest_portion: value['interest_portion'],
    loan: CrupdateLoanToJSON(value['loan']),
  }
}
