/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LoanStatus = {
  ACTIVE: 'ACTIVE',
  PAID: 'PAID',
  DEFAULTED: 'DEFAULTED',
} as const
export type LoanStatus = (typeof LoanStatus)[keyof typeof LoanStatus]

export function instanceOfLoanStatus(value: any): boolean {
  for (const key in LoanStatus) {
    if (Object.prototype.hasOwnProperty.call(LoanStatus, key)) {
      if (LoanStatus[key as keyof typeof LoanStatus] === value) {
        return true
      }
    }
  }
  return false
}

export function LoanStatusFromJSON(json: any): LoanStatus {
  return LoanStatusFromJSONTyped(json, false)
}

export function LoanStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoanStatus {
  return json as LoanStatus
}

export function LoanStatusToJSON(value?: LoanStatus | null): any {
  return value as any
}

export function LoanStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): LoanStatus {
  return value as LoanStatus
}
