/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const MaintenanceScheduleStatus = {
  PENDING: 'PENDING',
  DONE: 'DONE',
  SKIPPED: 'SKIPPED',
} as const
export type MaintenanceScheduleStatus =
  (typeof MaintenanceScheduleStatus)[keyof typeof MaintenanceScheduleStatus]

export function instanceOfMaintenanceScheduleStatus(value: any): boolean {
  for (const key in MaintenanceScheduleStatus) {
    if (Object.prototype.hasOwnProperty.call(MaintenanceScheduleStatus, key)) {
      if (MaintenanceScheduleStatus[key as keyof typeof MaintenanceScheduleStatus] === value) {
        return true
      }
    }
  }
  return false
}

export function MaintenanceScheduleStatusFromJSON(json: any): MaintenanceScheduleStatus {
  return MaintenanceScheduleStatusFromJSONTyped(json, false)
}

export function MaintenanceScheduleStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MaintenanceScheduleStatus {
  return json as MaintenanceScheduleStatus
}

export function MaintenanceScheduleStatusToJSON(value?: MaintenanceScheduleStatus | null): any {
  return value as any
}

export function MaintenanceScheduleStatusToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): MaintenanceScheduleStatus {
  return value as MaintenanceScheduleStatus
}
