/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CrupdateExpenseMoney } from './CrupdateExpenseMoney'
import {
  CrupdateExpenseMoneyFromJSON,
  CrupdateExpenseMoneyFromJSONTyped,
  CrupdateExpenseMoneyToJSON,
  CrupdateExpenseMoneyToJSONTyped,
} from './CrupdateExpenseMoney'

/**
 *
 * @export
 * @interface Maintenance
 */
export interface Maintenance {
  /**
   *
   * @type {string}
   * @memberof Maintenance
   */
  id?: string
  /**
   *
   * @type {CrupdateExpenseMoney}
   * @memberof Maintenance
   */
  expense?: CrupdateExpenseMoney
  /**
   * ID of the equipment this maintenance belongs to
   * @type {string}
   * @memberof Maintenance
   */
  equipment_id?: string
  /**
   *
   * @type {string}
   * @memberof Maintenance
   */
  description?: string
}

/**
 * Check if a given object implements the Maintenance interface.
 */
export function instanceOfMaintenance(value: object): value is Maintenance {
  return true
}

export function MaintenanceFromJSON(json: any): Maintenance {
  return MaintenanceFromJSONTyped(json, false)
}

export function MaintenanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Maintenance {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    expense: json['expense'] == null ? undefined : CrupdateExpenseMoneyFromJSON(json['expense']),
    equipment_id: json['equipment_id'] == null ? undefined : json['equipment_id'],
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function MaintenanceToJSON(json: any): Maintenance {
  return MaintenanceToJSONTyped(json, false)
}

export function MaintenanceToJSONTyped(
  value?: Maintenance | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    expense: CrupdateExpenseMoneyToJSON(value['expense']),
    equipment_id: value['equipment_id'],
    description: value['description'],
  }
}
