/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Warehouse } from './Warehouse'
import {
  WarehouseFromJSON,
  WarehouseFromJSONTyped,
  WarehouseToJSON,
  WarehouseToJSONTyped,
} from './Warehouse'
import type { CrupdateMaterial } from './CrupdateMaterial'
import {
  CrupdateMaterialFromJSON,
  CrupdateMaterialFromJSONTyped,
  CrupdateMaterialToJSON,
  CrupdateMaterialToJSONTyped,
} from './CrupdateMaterial'

/**
 *
 * @export
 * @interface MaterialWarehouseView
 */
export interface MaterialWarehouseView {
  /**
   *
   * @type {CrupdateMaterial}
   * @memberof MaterialWarehouseView
   */
  material?: CrupdateMaterial
  /**
   *
   * @type {Warehouse}
   * @memberof MaterialWarehouseView
   */
  warehouse?: Warehouse
  /**
   *
   * @type {number}
   * @memberof MaterialWarehouseView
   */
  quantity?: number
}

/**
 * Check if a given object implements the MaterialWarehouseView interface.
 */
export function instanceOfMaterialWarehouseView(value: object): value is MaterialWarehouseView {
  return true
}

export function MaterialWarehouseViewFromJSON(json: any): MaterialWarehouseView {
  return MaterialWarehouseViewFromJSONTyped(json, false)
}

export function MaterialWarehouseViewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MaterialWarehouseView {
  if (json == null) {
    return json
  }
  return {
    material: json['material'] == null ? undefined : CrupdateMaterialFromJSON(json['material']),
    warehouse: json['warehouse'] == null ? undefined : WarehouseFromJSON(json['warehouse']),
    quantity: json['quantity'] == null ? undefined : json['quantity'],
  }
}

export function MaterialWarehouseViewToJSON(json: any): MaterialWarehouseView {
  return MaterialWarehouseViewToJSONTyped(json, false)
}

export function MaterialWarehouseViewToJSONTyped(
  value?: MaterialWarehouseView | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    material: CrupdateMaterialToJSON(value['material']),
    warehouse: WarehouseToJSON(value['warehouse']),
    quantity: value['quantity'],
  }
}
