/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface MonetaryMovement
 */
export interface MonetaryMovement {
  /**
   *
   * @type {number}
   * @memberof MonetaryMovement
   */
  amount?: number
  /**
   *
   * @type {string}
   * @memberof MonetaryMovement
   */
  description?: string
}

/**
 * Check if a given object implements the MonetaryMovement interface.
 */
export function instanceOfMonetaryMovement(value: object): value is MonetaryMovement {
  return true
}

export function MonetaryMovementFromJSON(json: any): MonetaryMovement {
  return MonetaryMovementFromJSONTyped(json, false)
}

export function MonetaryMovementFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MonetaryMovement {
  if (json == null) {
    return json
  }
  return {
    amount: json['amount'] == null ? undefined : json['amount'],
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function MonetaryMovementToJSON(json: any): MonetaryMovement {
  return MonetaryMovementToJSONTyped(json, false)
}

export function MonetaryMovementToJSONTyped(
  value?: MonetaryMovement | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    amount: value['amount'],
    description: value['description'],
  }
}
