/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'

/**
 *
 * @export
 * @interface MonetaryMovement
 */
export interface MonetaryMovement {
  /**
   *
   * @type {string}
   * @memberof MonetaryMovement
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof MonetaryMovement
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof MonetaryMovement
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof MonetaryMovement
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof MonetaryMovement
   */
  updated_by?: AuditUser
  /**
   *
   * @type {number}
   * @memberof MonetaryMovement
   */
  amount?: number
  /**
   *
   * @type {string}
   * @memberof MonetaryMovement
   */
  description?: string
}

/**
 * Check if a given object implements the MonetaryMovement interface.
 */
export function instanceOfMonetaryMovement(value: object): value is MonetaryMovement {
  return true
}

export function MonetaryMovementFromJSON(json: any): MonetaryMovement {
  return MonetaryMovementFromJSONTyped(json, false)
}

export function MonetaryMovementFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MonetaryMovement {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    amount: json['amount'] == null ? undefined : json['amount'],
    description: json['description'] == null ? undefined : json['description'],
  }
}

export function MonetaryMovementToJSON(json: any): MonetaryMovement {
  return MonetaryMovementToJSONTyped(json, false)
}

export function MonetaryMovementToJSONTyped(
  value?: MonetaryMovement | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    amount: value['amount'],
    description: value['description'],
  }
}
