/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface MonetaryBreakdownResponse
 */
export interface MonetaryBreakdownResponse {
  /**
   *
   * @type {Array<object>}
   * @memberof MonetaryBreakdownResponse
   */
  expenses_by_type?: Array<object>
  /**
   *
   * @type {Array<object>}
   * @memberof MonetaryBreakdownResponse
   */
  budget_vs_actual?: Array<object>
  /**
   *
   * @type {Array<object>}
   * @memberof MonetaryBreakdownResponse
   */
  expected_vs_actual?: Array<object>
  /**
   *
   * @type {Array<object>}
   * @memberof MonetaryBreakdownResponse
   */
  revenue_by_job?: Array<object>
  /**
   *
   * @type {Array<object>}
   * @memberof MonetaryBreakdownResponse
   */
  expense_by_job?: Array<object>
  /**
   *
   * @type {Array<object>}
   * @memberof MonetaryBreakdownResponse
   */
  profitability_by_job?: Array<object>
  /**
   *
   * @type {Array<object>}
   * @memberof MonetaryBreakdownResponse
   */
  active_loans?: Array<object>
}

/**
 * Check if a given object implements the MonetaryBreakdownResponse interface.
 */
export function instanceOfMonetaryBreakdownResponse(
  value: object,
): value is MonetaryBreakdownResponse {
  return true
}

export function MonetaryBreakdownResponseFromJSON(json: any): MonetaryBreakdownResponse {
  return MonetaryBreakdownResponseFromJSONTyped(json, false)
}

export function MonetaryBreakdownResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MonetaryBreakdownResponse {
  if (json == null) {
    return json
  }
  return {
    expenses_by_type: json['expenses_by_type'] == null ? undefined : json['expenses_by_type'],
    budget_vs_actual: json['budget_vs_actual'] == null ? undefined : json['budget_vs_actual'],
    expected_vs_actual: json['expected_vs_actual'] == null ? undefined : json['expected_vs_actual'],
    revenue_by_job: json['revenue_by_job'] == null ? undefined : json['revenue_by_job'],
    expense_by_job: json['expense_by_job'] == null ? undefined : json['expense_by_job'],
    profitability_by_job:
      json['profitability_by_job'] == null ? undefined : json['profitability_by_job'],
    active_loans: json['active_loans'] == null ? undefined : json['active_loans'],
  }
}

export function MonetaryBreakdownResponseToJSON(json: any): MonetaryBreakdownResponse {
  return MonetaryBreakdownResponseToJSONTyped(json, false)
}

export function MonetaryBreakdownResponseToJSONTyped(
  value?: MonetaryBreakdownResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    expenses_by_type: value['expenses_by_type'],
    budget_vs_actual: value['budget_vs_actual'],
    expected_vs_actual: value['expected_vs_actual'],
    revenue_by_job: value['revenue_by_job'],
    expense_by_job: value['expense_by_job'],
    profitability_by_job: value['profitability_by_job'],
    active_loans: value['active_loans'],
  }
}
