/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface NotAuthorizedException
 */
export interface NotAuthorizedException {
  /**
   *
   * @type {string}
   * @memberof NotAuthorizedException
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof NotAuthorizedException
   */
  message?: string
}

/**
 * Check if a given object implements the NotAuthorizedException interface.
 */
export function instanceOfNotAuthorizedException(value: object): value is NotAuthorizedException {
  return true
}

export function NotAuthorizedExceptionFromJSON(json: any): NotAuthorizedException {
  return NotAuthorizedExceptionFromJSONTyped(json, false)
}

export function NotAuthorizedExceptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NotAuthorizedException {
  if (json == null) {
    return json
  }
  return {
    type: json['type'] == null ? undefined : json['type'],
    message: json['message'] == null ? undefined : json['message'],
  }
}

export function NotAuthorizedExceptionToJSON(json: any): NotAuthorizedException {
  return NotAuthorizedExceptionToJSONTyped(json, false)
}

export function NotAuthorizedExceptionToJSONTyped(
  value?: NotAuthorizedException | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    type: value['type'],
    message: value['message'],
  }
}
