/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CrupdateUser } from './CrupdateUser'
import {
  CrupdateUserFromJSON,
  CrupdateUserFromJSONTyped,
  CrupdateUserToJSON,
  CrupdateUserToJSONTyped,
} from './CrupdateUser'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'

/**
 *
 * @export
 * @interface Notification
 */
export interface Notification {
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof Notification
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof Notification
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof Notification
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof Notification
   */
  updated_by?: AuditUser
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  id?: string
  /**
   *
   * @type {CrupdateUser}
   * @memberof Notification
   */
  user?: CrupdateUser
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  task_id?: string | null
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  message?: string | null
  /**
   *
   * @type {boolean}
   * @memberof Notification
   */
  read?: boolean
  /**
   *
   * @type {Date}
   * @memberof Notification
   */
  read_at?: Date | null
  /**
   *
   * @type {boolean}
   * @memberof Notification
   */
  completed?: boolean
  /**
   *
   * @type {Date}
   * @memberof Notification
   */
  completed_at?: Date | null
  /**
   *
   * @type {boolean}
   * @memberof Notification
   */
  effective_completed?: boolean
}

/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
  return true
}

export function NotificationFromJSON(json: any): Notification {
  return NotificationFromJSONTyped(json, false)
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    id: json['id'] == null ? undefined : json['id'],
    user: json['user'] == null ? undefined : CrupdateUserFromJSON(json['user']),
    task_id: json['task_id'] == null ? undefined : json['task_id'],
    title: json['title'] == null ? undefined : json['title'],
    message: json['message'] == null ? undefined : json['message'],
    read: json['read'] == null ? undefined : json['read'],
    read_at: json['read_at'] == null ? undefined : new Date(json['read_at']),
    completed: json['completed'] == null ? undefined : json['completed'],
    completed_at: json['completed_at'] == null ? undefined : new Date(json['completed_at']),
    effective_completed:
      json['effective_completed'] == null ? undefined : json['effective_completed'],
  }
}

export function NotificationToJSON(json: any): Notification {
  return NotificationToJSONTyped(json, false)
}

export function NotificationToJSONTyped(
  value?: Notification | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    id: value['id'],
    user: CrupdateUserToJSON(value['user']),
    task_id: value['task_id'],
    title: value['title'],
    message: value['message'],
    read: value['read'],
    read_at: value['read_at'] == null ? value['read_at'] : value['read_at'].toISOString(),
    completed: value['completed'],
    completed_at:
      value['completed_at'] == null ? value['completed_at'] : value['completed_at'].toISOString(),
    effective_completed: value['effective_completed'],
  }
}
