/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginatedResponse
 */
export interface PaginatedResponse {
    /**
     * 
     * @type {Array<object>}
     * @memberof PaginatedResponse
     */
    data?: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the PaginatedResponse interface.
 */
export function instanceOfPaginatedResponse(value: object): value is PaginatedResponse {
    return true;
}

export function PaginatedResponseFromJSON(json: any): PaginatedResponse {
    return PaginatedResponseFromJSONTyped(json, false);
}

export function PaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function PaginatedResponseToJSON(json: any): PaginatedResponse {
    return PaginatedResponseToJSONTyped(json, false);
}

export function PaginatedResponseToJSONTyped(value?: PaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'total': value['total'],
    };
}

