/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PurchaseOrderLine } from './PurchaseOrderLine';
import {
    PurchaseOrderLineFromJSON,
    PurchaseOrderLineFromJSONTyped,
    PurchaseOrderLineToJSON,
    PurchaseOrderLineToJSONTyped,
} from './PurchaseOrderLine';
import type { PurchaseOrderStatus } from './PurchaseOrderStatus';
import {
    PurchaseOrderStatusFromJSON,
    PurchaseOrderStatusFromJSONTyped,
    PurchaseOrderStatusToJSON,
    PurchaseOrderStatusToJSONTyped,
} from './PurchaseOrderStatus';

/**
 * 
 * @export
 * @interface PurchaseOrder
 */
export interface PurchaseOrder {
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrder
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrder
     */
    supplier_id?: string;
    /**
     * 
     * @type {Date}
     * @memberof PurchaseOrder
     */
    order_date?: Date;
    /**
     * 
     * @type {PurchaseOrderStatus}
     * @memberof PurchaseOrder
     */
    status?: PurchaseOrderStatus;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrder
     */
    total_amount?: number;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrder
     */
    company_id?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrder
     */
    job_id?: string;
    /**
     * 
     * @type {Array<PurchaseOrderLine>}
     * @memberof PurchaseOrder
     */
    lines?: Array<PurchaseOrderLine>;
}



/**
 * Check if a given object implements the PurchaseOrder interface.
 */
export function instanceOfPurchaseOrder(value: object): value is PurchaseOrder {
    return true;
}

export function PurchaseOrderFromJSON(json: any): PurchaseOrder {
    return PurchaseOrderFromJSONTyped(json, false);
}

export function PurchaseOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'supplier_id': json['supplier_id'] == null ? undefined : json['supplier_id'],
        'order_date': json['order_date'] == null ? undefined : (new Date(json['order_date'])),
        'status': json['status'] == null ? undefined : PurchaseOrderStatusFromJSON(json['status']),
        'total_amount': json['total_amount'] == null ? undefined : json['total_amount'],
        'company_id': json['company_id'] == null ? undefined : json['company_id'],
        'job_id': json['job_id'] == null ? undefined : json['job_id'],
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(PurchaseOrderLineFromJSON)),
    };
}

export function PurchaseOrderToJSON(json: any): PurchaseOrder {
    return PurchaseOrderToJSONTyped(json, false);
}

export function PurchaseOrderToJSONTyped(value?: PurchaseOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'supplier_id': value['supplier_id'],
        'order_date': value['order_date'] == null ? value['order_date'] : value['order_date'].toISOString().substring(0,10),
        'status': PurchaseOrderStatusToJSON(value['status']),
        'total_amount': value['total_amount'],
        'company_id': value['company_id'],
        'job_id': value['job_id'],
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(PurchaseOrderLineToJSON)),
    };
}

