/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PurchaseOrderLine
 */
export interface PurchaseOrderLine {
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderLine
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOrderLine
     */
    material_id?: string;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrderLine
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrderLine
     */
    unit_price?: number;
}

/**
 * Check if a given object implements the PurchaseOrderLine interface.
 */
export function instanceOfPurchaseOrderLine(value: object): value is PurchaseOrderLine {
    return true;
}

export function PurchaseOrderLineFromJSON(json: any): PurchaseOrderLine {
    return PurchaseOrderLineFromJSONTyped(json, false);
}

export function PurchaseOrderLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOrderLine {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'material_id': json['material_id'] == null ? undefined : json['material_id'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'unit_price': json['unit_price'] == null ? undefined : json['unit_price'],
    };
}

export function PurchaseOrderLineToJSON(json: any): PurchaseOrderLine {
    return PurchaseOrderLineToJSONTyped(json, false);
}

export function PurchaseOrderLineToJSONTyped(value?: PurchaseOrderLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'material_id': value['material_id'],
        'quantity': value['quantity'],
        'unit_price': value['unit_price'],
    };
}

