/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { PurchaseOperationTravel } from './PurchaseOperationTravel'
import {
  PurchaseOperationTravelFromJSON,
  PurchaseOperationTravelFromJSONTyped,
  PurchaseOperationTravelToJSON,
  PurchaseOperationTravelToJSONTyped,
} from './PurchaseOperationTravel'
import type { PurchaseOperationEquipmentLine } from './PurchaseOperationEquipmentLine'
import {
  PurchaseOperationEquipmentLineFromJSON,
  PurchaseOperationEquipmentLineFromJSONTyped,
  PurchaseOperationEquipmentLineToJSON,
  PurchaseOperationEquipmentLineToJSONTyped,
} from './PurchaseOperationEquipmentLine'
import type { PurchaseOperationMaterialLine } from './PurchaseOperationMaterialLine'
import {
  PurchaseOperationMaterialLineFromJSON,
  PurchaseOperationMaterialLineFromJSONTyped,
  PurchaseOperationMaterialLineToJSON,
  PurchaseOperationMaterialLineToJSONTyped,
} from './PurchaseOperationMaterialLine'

/**
 *
 * @export
 * @interface PurchaseOperationRequest
 */
export interface PurchaseOperationRequest {
  /**
   *
   * @type {string}
   * @memberof PurchaseOperationRequest
   */
  comment?: string
  /**
   *
   * @type {Array<PurchaseOperationEquipmentLine>}
   * @memberof PurchaseOperationRequest
   */
  equipment_lines?: Array<PurchaseOperationEquipmentLine>
  /**
   *
   * @type {Array<PurchaseOperationMaterialLine>}
   * @memberof PurchaseOperationRequest
   */
  material_lines?: Array<PurchaseOperationMaterialLine>
  /**
   *
   * @type {PurchaseOperationTravel}
   * @memberof PurchaseOperationRequest
   */
  travel?: PurchaseOperationTravel
}

/**
 * Check if a given object implements the PurchaseOperationRequest interface.
 */
export function instanceOfPurchaseOperationRequest(
  value: object,
): value is PurchaseOperationRequest {
  return true
}

export function PurchaseOperationRequestFromJSON(json: any): PurchaseOperationRequest {
  return PurchaseOperationRequestFromJSONTyped(json, false)
}

export function PurchaseOperationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PurchaseOperationRequest {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    equipment_lines:
      json['equipment_lines'] == null
        ? undefined
        : (json['equipment_lines'] as Array<any>).map(PurchaseOperationEquipmentLineFromJSON),
    material_lines:
      json['material_lines'] == null
        ? undefined
        : (json['material_lines'] as Array<any>).map(PurchaseOperationMaterialLineFromJSON),
    travel: json['travel'] == null ? undefined : PurchaseOperationTravelFromJSON(json['travel']),
  }
}

export function PurchaseOperationRequestToJSON(json: any): PurchaseOperationRequest {
  return PurchaseOperationRequestToJSONTyped(json, false)
}

export function PurchaseOperationRequestToJSONTyped(
  value?: PurchaseOperationRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    equipment_lines:
      value['equipment_lines'] == null
        ? undefined
        : (value['equipment_lines'] as Array<any>).map(PurchaseOperationEquipmentLineToJSON),
    material_lines:
      value['material_lines'] == null
        ? undefined
        : (value['material_lines'] as Array<any>).map(PurchaseOperationMaterialLineToJSON),
    travel: PurchaseOperationTravelToJSON(value['travel']),
  }
}
