/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrupdateEquipment } from './CrupdateEquipment';
import {
    CrupdateEquipmentFromJSON,
    CrupdateEquipmentFromJSONTyped,
    CrupdateEquipmentToJSON,
    CrupdateEquipmentToJSONTyped,
} from './CrupdateEquipment';

/**
 * 
 * @export
 * @interface PurchaseOperationEquipmentLine
 */
export interface PurchaseOperationEquipmentLine {
    /**
     * 
     * @type {CrupdateEquipment}
     * @memberof PurchaseOperationEquipmentLine
     */
    equipment?: CrupdateEquipment;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOperationEquipmentLine
     */
    expense_id?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOperationEquipmentLine
     */
    purchase_id?: string;
    /**
     * 
     * @type {string}
     * @memberof PurchaseOperationEquipmentLine
     */
    travel_equipment_id?: string;
    /**
     * 
     * @type {number}
     * @memberof PurchaseOperationEquipmentLine
     */
    unit_price?: number;
}

/**
 * Check if a given object implements the PurchaseOperationEquipmentLine interface.
 */
export function instanceOfPurchaseOperationEquipmentLine(value: object): value is PurchaseOperationEquipmentLine {
    return true;
}

export function PurchaseOperationEquipmentLineFromJSON(json: any): PurchaseOperationEquipmentLine {
    return PurchaseOperationEquipmentLineFromJSONTyped(json, false);
}

export function PurchaseOperationEquipmentLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOperationEquipmentLine {
    if (json == null) {
        return json;
    }
    return {
        
        'equipment': json['equipment'] == null ? undefined : CrupdateEquipmentFromJSON(json['equipment']),
        'expense_id': json['expense_id'] == null ? undefined : json['expense_id'],
        'purchase_id': json['purchase_id'] == null ? undefined : json['purchase_id'],
        'travel_equipment_id': json['travel_equipment_id'] == null ? undefined : json['travel_equipment_id'],
        'unit_price': json['unit_price'] == null ? undefined : json['unit_price'],
    };
}

export function PurchaseOperationEquipmentLineToJSON(json: any): PurchaseOperationEquipmentLine {
    return PurchaseOperationEquipmentLineToJSONTyped(json, false);
}

export function PurchaseOperationEquipmentLineToJSONTyped(value?: PurchaseOperationEquipmentLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'equipment': CrupdateEquipmentToJSON(value['equipment']),
        'expense_id': value['expense_id'],
        'purchase_id': value['purchase_id'],
        'travel_equipment_id': value['travel_equipment_id'],
        'unit_price': value['unit_price'],
    };
}

