/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CrupdateExpenseMoney } from './CrupdateExpenseMoney'
import {
  CrupdateExpenseMoneyFromJSON,
  CrupdateExpenseMoneyFromJSONTyped,
  CrupdateExpenseMoneyToJSON,
  CrupdateExpenseMoneyToJSONTyped,
} from './CrupdateExpenseMoney'
import type { CrupdateEquipment } from './CrupdateEquipment'
import {
  CrupdateEquipmentFromJSON,
  CrupdateEquipmentFromJSONTyped,
  CrupdateEquipmentToJSON,
  CrupdateEquipmentToJSONTyped,
} from './CrupdateEquipment'
import type { CrupdateMaterial } from './CrupdateMaterial'
import {
  CrupdateMaterialFromJSON,
  CrupdateMaterialFromJSONTyped,
  CrupdateMaterialToJSON,
  CrupdateMaterialToJSONTyped,
} from './CrupdateMaterial'

/**
 *
 * @export
 * @interface Purchase
 */
export interface Purchase {
  /**
   *
   * @type {string}
   * @memberof Purchase
   */
  id?: string
  /**
   *
   * @type {CrupdateExpenseMoney}
   * @memberof Purchase
   */
  expense?: CrupdateExpenseMoney
  /**
   *
   * @type {string}
   * @memberof Purchase
   */
  supplier?: string
  /**
   *
   * @type {CrupdateEquipment}
   * @memberof Purchase
   */
  equipment?: CrupdateEquipment
  /**
   *
   * @type {CrupdateMaterial}
   * @memberof Purchase
   */
  material?: CrupdateMaterial
  /**
   *
   * @type {number}
   * @memberof Purchase
   */
  quantity?: number
  /**
   *
   * @type {boolean}
   * @memberof Purchase
   */
  is_equipment?: boolean
}

/**
 * Check if a given object implements the Purchase interface.
 */
export function instanceOfPurchase(value: object): value is Purchase {
  return true
}

export function PurchaseFromJSON(json: any): Purchase {
  return PurchaseFromJSONTyped(json, false)
}

export function PurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Purchase {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    expense: json['expense'] == null ? undefined : CrupdateExpenseMoneyFromJSON(json['expense']),
    supplier: json['supplier'] == null ? undefined : json['supplier'],
    equipment: json['equipment'] == null ? undefined : CrupdateEquipmentFromJSON(json['equipment']),
    material: json['material'] == null ? undefined : CrupdateMaterialFromJSON(json['material']),
    quantity: json['quantity'] == null ? undefined : json['quantity'],
    is_equipment: json['is_equipment'] == null ? undefined : json['is_equipment'],
  }
}

export function PurchaseToJSON(json: any): Purchase {
  return PurchaseToJSONTyped(json, false)
}

export function PurchaseToJSONTyped(
  value?: Purchase | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    expense: CrupdateExpenseMoneyToJSON(value['expense']),
    supplier: value['supplier'],
    equipment: CrupdateEquipmentToJSON(value['equipment']),
    material: CrupdateMaterialToJSON(value['material']),
    quantity: value['quantity'],
    is_equipment: value['is_equipment'],
  }
}
