/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { User } from './User'
import { UserFromJSON, UserFromJSONTyped, UserToJSON, UserToJSONTyped } from './User'

/**
 *
 * @export
 * @interface Team
 */
export interface Team {
  /**
   *
   * @type {string}
   * @memberof Team
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Team
   */
  name?: string
  /**
   *
   * @type {User}
   * @memberof Team
   */
  leader?: User
  /**
   *
   * @type {Array<User>}
   * @memberof Team
   */
  members?: Array<User>
}

/**
 * Check if a given object implements the Team interface.
 */
export function instanceOfTeam(value: object): value is Team {
  return true
}

export function TeamFromJSON(json: any): Team {
  return TeamFromJSONTyped(json, false)
}

export function TeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Team {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    leader: json['leader'] == null ? undefined : UserFromJSON(json['leader']),
    members:
      json['members'] == null ? undefined : (json['members'] as Array<any>).map(UserFromJSON),
  }
}

export function TeamToJSON(json: any): Team {
  return TeamToJSONTyped(json, false)
}

export function TeamToJSONTyped(value?: Team | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    name: value['name'],
    leader: UserToJSON(value['leader']),
    members:
      value['members'] == null ? undefined : (value['members'] as Array<any>).map(UserToJSON),
  }
}
