/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSeriesResponsePeriod
 */
export interface TimeSeriesResponsePeriod {
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesResponsePeriod
     */
    from?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesResponsePeriod
     */
    to?: string;
}

/**
 * Check if a given object implements the TimeSeriesResponsePeriod interface.
 */
export function instanceOfTimeSeriesResponsePeriod(value: object): value is TimeSeriesResponsePeriod {
    return true;
}

export function TimeSeriesResponsePeriodFromJSON(json: any): TimeSeriesResponsePeriod {
    return TimeSeriesResponsePeriodFromJSONTyped(json, false);
}

export function TimeSeriesResponsePeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesResponsePeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : json['from'],
        'to': json['to'] == null ? undefined : json['to'],
    };
}

export function TimeSeriesResponsePeriodToJSON(json: any): TimeSeriesResponsePeriod {
    return TimeSeriesResponsePeriodToJSONTyped(json, false);
}

export function TimeSeriesResponsePeriodToJSONTyped(value?: TimeSeriesResponsePeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
    };
}

