/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CrupdateExpenseMoney } from './CrupdateExpenseMoney'
import {
  CrupdateExpenseMoneyFromJSON,
  CrupdateExpenseMoneyFromJSONTyped,
  CrupdateExpenseMoneyToJSON,
  CrupdateExpenseMoneyToJSONTyped,
} from './CrupdateExpenseMoney'
import type { CrupdateWarehouse } from './CrupdateWarehouse'
import {
  CrupdateWarehouseFromJSON,
  CrupdateWarehouseFromJSONTyped,
  CrupdateWarehouseToJSON,
  CrupdateWarehouseToJSONTyped,
} from './CrupdateWarehouse'

/**
 *
 * @export
 * @interface TravelExpense
 */
export interface TravelExpense {
  /**
   *
   * @type {string}
   * @memberof TravelExpense
   */
  id?: string
  /**
   *
   * @type {CrupdateExpenseMoney}
   * @memberof TravelExpense
   */
  expense?: CrupdateExpenseMoney
  /**
   *
   * @type {CrupdateWarehouse}
   * @memberof TravelExpense
   */
  departure_location?: CrupdateWarehouse
  /**
   *
   * @type {CrupdateWarehouse}
   * @memberof TravelExpense
   */
  arrival_location?: CrupdateWarehouse
  /**
   *
   * @type {Date}
   * @memberof TravelExpense
   */
  departure_date?: Date
  /**
   *
   * @type {Date}
   * @memberof TravelExpense
   */
  arrival_date?: Date
}

/**
 * Check if a given object implements the TravelExpense interface.
 */
export function instanceOfTravelExpense(value: object): value is TravelExpense {
  return true
}

export function TravelExpenseFromJSON(json: any): TravelExpense {
  return TravelExpenseFromJSONTyped(json, false)
}

export function TravelExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelExpense {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    expense: json['expense'] == null ? undefined : CrupdateExpenseMoneyFromJSON(json['expense']),
    departure_location:
      json['departure_location'] == null
        ? undefined
        : CrupdateWarehouseFromJSON(json['departure_location']),
    arrival_location:
      json['arrival_location'] == null
        ? undefined
        : CrupdateWarehouseFromJSON(json['arrival_location']),
    departure_date: json['departure_date'] == null ? undefined : new Date(json['departure_date']),
    arrival_date: json['arrival_date'] == null ? undefined : new Date(json['arrival_date']),
  }
}

export function TravelExpenseToJSON(json: any): TravelExpense {
  return TravelExpenseToJSONTyped(json, false)
}

export function TravelExpenseToJSONTyped(
  value?: TravelExpense | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    expense: CrupdateExpenseMoneyToJSON(value['expense']),
    departure_location: CrupdateWarehouseToJSON(value['departure_location']),
    arrival_location: CrupdateWarehouseToJSON(value['arrival_location']),
    departure_date:
      value['departure_date'] == null
        ? value['departure_date']
        : value['departure_date'].toISOString(),
    arrival_date:
      value['arrival_date'] == null ? value['arrival_date'] : value['arrival_date'].toISOString(),
  }
}
