/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrupdateEquipment } from './CrupdateEquipment';
import {
    CrupdateEquipmentFromJSON,
    CrupdateEquipmentFromJSONTyped,
    CrupdateEquipmentToJSON,
    CrupdateEquipmentToJSONTyped,
} from './CrupdateEquipment';

/**
 * 
 * @export
 * @interface TravelOperationEquipmentLine
 */
export interface TravelOperationEquipmentLine {
    /**
     * 
     * @type {string}
     * @memberof TravelOperationEquipmentLine
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelOperationEquipmentLine
     */
    id?: string;
    /**
     * 
     * @type {CrupdateEquipment}
     * @memberof TravelOperationEquipmentLine
     */
    equipment?: CrupdateEquipment;
}

/**
 * Check if a given object implements the TravelOperationEquipmentLine interface.
 */
export function instanceOfTravelOperationEquipmentLine(value: object): value is TravelOperationEquipmentLine {
    return true;
}

export function TravelOperationEquipmentLineFromJSON(json: any): TravelOperationEquipmentLine {
    return TravelOperationEquipmentLineFromJSONTyped(json, false);
}

export function TravelOperationEquipmentLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelOperationEquipmentLine {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        'id': json['id'] == null ? undefined : json['id'],
        'equipment': json['equipment'] == null ? undefined : CrupdateEquipmentFromJSON(json['equipment']),
    };
}

export function TravelOperationEquipmentLineToJSON(json: any): TravelOperationEquipmentLine {
    return TravelOperationEquipmentLineToJSONTyped(json, false);
}

export function TravelOperationEquipmentLineToJSONTyped(value?: TravelOperationEquipmentLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
        'id': value['id'],
        'equipment': CrupdateEquipmentToJSON(value['equipment']),
    };
}

