/* tslint:disable */
/* eslint-disable */
/**
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Role } from './Role'
import { RoleFromJSON, RoleFromJSONTyped, RoleToJSON, RoleToJSONTyped } from './Role'
import type { AuditUser } from './AuditUser'
import {
  AuditUserFromJSON,
  AuditUserFromJSONTyped,
  AuditUserToJSON,
  AuditUserToJSONTyped,
} from './AuditUser'
import type { Sex } from './Sex'
import { SexFromJSON, SexFromJSONTyped, SexToJSON, SexToJSONTyped } from './Sex'

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  comment?: string
  /**
   *
   * @type {Date}
   * @memberof User
   */
  created_at?: Date
  /**
   *
   * @type {Date}
   * @memberof User
   */
  updated_at?: Date
  /**
   *
   * @type {AuditUser}
   * @memberof User
   */
  created_by?: AuditUser
  /**
   *
   * @type {AuditUser}
   * @memberof User
   */
  updated_by?: AuditUser
  /**
   *
   * @type {string}
   * @memberof User
   */
  id?: string
  /**
   *
   * @type {Role}
   * @memberof User
   */
  role?: Role
  /**
   *
   * @type {string}
   * @memberof User
   */
  first_name?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  last_name?: string
  /**
   *
   * @type {Sex}
   * @memberof User
   */
  sex?: Sex
  /**
   *
   * @type {string}
   * @memberof User
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  company_id?: string
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  return true
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false)
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
  if (json == null) {
    return json
  }
  return {
    comment: json['comment'] == null ? undefined : json['comment'],
    created_at: json['created_at'] == null ? undefined : new Date(json['created_at']),
    updated_at: json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    created_by: json['created_by'] == null ? undefined : AuditUserFromJSON(json['created_by']),
    updated_by: json['updated_by'] == null ? undefined : AuditUserFromJSON(json['updated_by']),
    id: json['id'] == null ? undefined : json['id'],
    role: json['role'] == null ? undefined : RoleFromJSON(json['role']),
    first_name: json['first_name'] == null ? undefined : json['first_name'],
    last_name: json['last_name'] == null ? undefined : json['last_name'],
    sex: json['sex'] == null ? undefined : SexFromJSON(json['sex']),
    email: json['email'] == null ? undefined : json['email'],
    company_id: json['company_id'] == null ? undefined : json['company_id'],
  }
}

export function UserToJSON(json: any): User {
  return UserToJSONTyped(json, false)
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    comment: value['comment'],
    created_at:
      value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
    updated_at:
      value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    created_by: AuditUserToJSON(value['created_by']),
    updated_by: AuditUserToJSON(value['updated_by']),
    id: value['id'],
    role: RoleToJSON(value['role']),
    first_name: value['first_name'],
    last_name: value['last_name'],
    sex: SexToJSON(value['sex']),
    email: value['email'],
    company_id: value['company_id'],
  }
}
